### ISSUE TITLE
[Landing Page UX] Add new Dev Hub logo & header

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#103]
**Problem**
Currently, the Gigs Board name does not clearly communicate the focus of our platform, which is about the NEAR developer ecosystem. 

**Solution**
Change the name from Gigs Board to Dev Hub and add a header with better explanation.
![Image](https://user-images.githubusercontent.com/110252255/233211929-2d42d907-6b48-4bd1-a628-1a31ba29634c.png)

**Acceptance Criteria**
- Replace the existing header with two sections: Navbar and Header.
- Navbar
  - Visible on every page of the platform 
  - Include dimensions in design (62px height and 100% width with #181818 background fill)
  - Replace the current logo in the navbar with the attached logo. Logo should be vertically centered and left aligned.
 - Header: 
   - Visible only on the homepage
   - Include dimensions in design (250px height and 100% width with gradient fill)
   - Copy is vertically centered and centered aligned
- Change any breadcrumb that say Developer Governance to DevHub. Example: DevHub / Protocol / 

**Assets**
1) Copy
A decentralized community of
NEAR Developers
Share your ideas, match solutions, and access support and funding.

2) Logo: 
![Image](https://user-images.githubusercontent.com/110252255/233210564-50f49f00-813b-4079-80d4-a42ae5baee13.svg)

**Comment by sumitshinde-84** [comment]
i  would like to work on it, can you please assign it to me .

**Comment by ailisp** [comment]
Thanks @sumitshinde-84 for your help! it is already done in [github board](https://github.com/orgs/near/projects/60), however we forget to close the issue. Please indicate your interest in other tickets on the board!
