### ISSUE TITLE
Posts in feed are not rendering text properly

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#109]
**Describe the bug**
After launching https://github.com/near/neardevhub-widgets/issues/84, the condense post functionality is not working in Safari browser and rendering jumbled text for some posts in the feed.

**To Reproduce**
1. Go to http://neardevhub.org
2. Look at posts in the feed
3. Posts render incorrectly (e.g. text is overlapping with each other)

**Expected behavior**
User should see the Read More button instead of the jumbled text.

**Screenshots**
![Screenshot 2023-04-24 at 12 05 25 PM](https://user-images.githubusercontent.com/110252255/234091825-1eef5146-85ac-4637-8667-ca11ca906cfe.png)
![Screenshot 2023-04-24 at 12 05 41 PM](https://user-images.githubusercontent.com/110252255/234091869-f860e116-dcb6-4cc9-83a6-953d1f0975ba.png)

**Desktop (please complete the following information):**
 - OS: Safari
 - Browser: Safari
 - Version: Version 16.4 (18615.1.26.11.22)

**Comment by ailisp** [comment]
The bug is due to safari doesn't support webkit-line-clamp when there is block element (a lot of them in markdown). So only reliable way maybe do clamp in js
