### ISSUE TITLE
[Notifications] Rename notifications and Reposts to DevHub

### ISSUE THREAD

**Issue by nearmax** [near/neardevhub-widgets#110]
Currently notifications say:
* "liked your Developer Governance post"
* "View Developer Governance Post"

And reposts to social mainpage say:
* "Posted on Developer DAO Board"

Instead it should say:
* "liked your DevHub post"
* "View DevHub Post"
* "Posted on DevHub"

The first two can be changed in this widgets repo. The last one needs a smart-contract change.

**Comment by ben-jamming-reilly** [comment]
@ori-near I'd like to take this one as well

**Comment by Tguntenaar** [comment]
I can also pick this up. @ailisp could you assign me

**Comment by near-akaia-root** [comment]
Assigned @Tguntenaar

**Comment by Tguntenaar** [comment]
@near-akaia-root Could you move this to 'in progress'?

**Comment by frol** [comment]
Resolved in #186
