### ISSUE TITLE
Opening post in a new tab should reveal the full post

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#113]
**Describe the bug**
When a user clicks to open any post in a new tab, the condense post behavior (https://github.com/near/neardevhub-widgets/issues/84) applies. This means that the user needs to click again on "Read More" to read the post. While the condense post behavior is useful on the homepage feed or search results where the user sees many posts, it is less useful on the actual post. 

**To Reproduce**
1. Go to http://neardevhub.org
2. Click on the "Open in a new tab" icon for any post
3. Post renders with "Read more"

**Expected behavior**
When a user goes to a specific post URL, user should see the full post and comments without the collapse.

**Screenshots**
![Screenshot 2023-04-25 at 4 01 29 PM](https://user-images.githubusercontent.com/110252255/234425636-37fadd24-25b9-40a9-b056-2850d8829ccf.png)

**Desktop:**
 - OS: Safari
 - Browser: Safari
 - Version: Version 16.4 (18615.1.26.11.22)

**Comment by ori-near** [comment]
Note: I realize this bug was potentially caused by design with the acceptance criteria:
`Posts should get condensed consistently across the platform (e.g. feed, search results, etc)`

Would like to exclude full posts from this please. Thank you!

**Comment by projectnoa** [comment]
I would like to address this issue as my first contribution.

**Comment by ori-near** [comment]
Hi @projectnoa – thanks so much for expressing interest 🔥. We appreciate your willingness to contribute! 

We have assigned this ticket to you and would like to kindly request that you submit a pull request with your solution within one week. If you are no longer able to work on this issue, please let us know so we can reopen it for another developer to take on. Once again, thanks so much and we look forward to your contribution.

**Comment by ori-near** [comment]
Hi @projectnoa – How's it going? Just wanted to check in on this. Thanks so much.

**Comment by projectnoa** [comment]
> Hi @projectnoa – How's it going? Just wanted to check in on this. Thanks so much.

Hi @ori-near, sorry for the delay. I was struggling with the process of testing my changes since it seems that I have to have a Wallet and have money on it to test on the NEAR social website.

Let me know your observations on my change. 

Thanks!

**Comment by ori-near** [comment]
No worries @projectnoa – it looks like your merge was approved. Thanks so much for your contribution 🙏.
