### ISSUE TITLE
[Landing Page UX] Simplify search / filter UI experience

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#114]
**Problem**
Currently, the search and filter UI display too many elements (6 buttons and 3 search fields), making it confusing for users to navigate through the various posts on the feed:
![Screenshot 2023-04-25 at 5 15 53 PM](https://user-images.githubusercontent.com/110252255/234435076-51bf948b-ca6b-4821-8246-bb9f004a87de.png)

**Solution**
This ticket introduces a simplified search and filter UI of one search box and three dropdown filter buttons.
![Screenshot 2023-04-25 at 5 48 24 PM](https://user-images.githubusercontent.com/110252255/234438195-69204014-f0d4-42ef-896d-d06c5423b0e7.png)

**Scope**
The scope of this ticket is to replace the existing 9 fields with the 4 new ones. There will be separate tickets to address the create experience, boards, and sorting functionality.

**User Story**
As a user, I want to have a simplified search and filter UI experience so that I can easily find posts. 

**Acceptance Criteria**

- A user sees the updated search/filter UI elements (Search box, Sort dropdown, Author dropdown, and Label dropdown) per the design
- The search box has a minor UI change per the design with no functionality change
- The sort label will have a dropdown with three options:
  - Latest – This is the default selection. It loads the most recent top-level posts and replaces the existing home button
  - Hottest – This shows the most popular posts and replaces the existing hottest button
  - All replies – This shows all the replies (both parent or child level) in most recent order and replaces the existing recent button
- The author and label sort dropdowns reveal a search box with the list of labels or authors.

**Attachments**
Figma design: 
https://www.figma.com/file/nTfDxzBc1RbjMxUA0bqKNF/Search-%2F-Filter-UI?node-id=0%3A1&t=7dCdqS2Y1QqAqnpd-1

**Comment by ori-near** [comment]
@ailisp Can you please size this and let me know if you have any questions? I assume this might be a `good first issue` ticket? If so, can you please add that label? Thank you.

**Comment by ailisp** [comment]
The author and Label dropdown is a dropdown with a search box. It resembles github's issue filter by author / label and needs to implemented as a nearsocial widget. We cannot reuse TypeAhead component given required functionality is not exported by nearsocial viewer. I expect this part would takes some time so I make the estimation to 3 days.

**Comment by ben-jamming-reilly** [comment]
@ori-near Would love to take up this ticket

**Comment by ori-near** [comment]
Hi @ben-jamming-reilly – just wanted to check in on this ticket and see if you need anything from @ailisp or @frol?

**Comment by frol** [comment]
@ori-near It seems that it was addressed in #122. Can you check DevHub and submit a new issue if there is anything that is left to be implemented?
