### ISSUE TITLE
[Create post] Enable user tagging/mentions preview in post editing

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#119]
**Problem**
Currently, DevHub users are unable to easily and accurately tag other users on our platform due to a missing tagging/mentions system. This means that users may potentially tag the wrong person or a user that does not exist, making it more difficult to interact with others. This ticket introduces a tagging/mentions ability.

**User Story**
As a user, I need to easily tag other users in posts, so that I can interact with them effectively and avoid any confusion or mistakes. 

**Scope**
This user story is focusing on enabling the tagging/mention UI. We will create a separate story for actually implementing the notification.

**Acceptance Criteria**
- When a user types "@" followed by the first couple of letters of a person's name or username, a list of suggested users should appear
- The suggested user list should include the user's profile picture, username, and name for easy identification
- The suggested user list should update in real time as the user continues to type
- The user can select the correct user from the suggested list, and their username should appear as plain text in the post in editing mode as it does with existing functionality (e.g. @username)
- Similar to the existing functionality, the username should render in the preview mode below the edit post and in the final published version with the username profile and first and last names (or username if the name is unavailable) with a link to their profile. When a user hovers over the name, the existing profile dialogue should render.
- If a user manually types username, the same rendering functionality should apply as the previous acceptance criteria
- If a user tries to tag a user that does not exist, an error message or indication should appear to explain that the user is not found
- There should be a way to type the "@" symbol without triggering the user mention feature, such as when writing an email address, when entering space after the @ symbol, or a special character such as " before the @ symbol.

**Examples:**
https://near.org has this functionality: ![Screenshot 2023-05-02 at 1 55 46 PM](https://user-images.githubusercontent.com/110252255/235784113-4b54c68d-65e6-4b94-b77e-6b47c92befbd.png)

![Screenshot 2023-05-02 at 1 57 51 PM](https://user-images.githubusercontent.com/110252255/235784472-2cdb8989-075f-43ef-b20b-58ea9ed20561.png)

![Screenshot 2023-05-02 at 1 58 24 PM](https://user-images.githubusercontent.com/110252255/235784577-bc23b55a-5940-4fb7-8746-2fc3a484994b.png)

**Comment by ori-near** [comment]
Hi @ailisp can you please let me know if you have any questions and add a size estimate to this? Also, is this a good first issue?

**Comment by ailisp** [comment]
@ori-near where do you find it? I couldn't trigger it from near.org

<img width="477" alt="image" src="https://user-images.githubusercontent.com/13259400/235923459-44dfbb7f-be75-4572-b860-56c770629545.png">

Assume it's available in some widget in near.org, I think it is a one day task to locate and integrate it to DevHub

**Comment by ailisp** [comment]
@ori-near sorry it works for me now. Please assign this to Thomas (@Tguntenaar) He is interested to take this one. For some reason github doesn't allow me to assign him

**Comment by ori-near** [comment]
Hi @ailisp – I just spoke with Peter about taking this one, since he's working on a similar notification ticket (#52). I would prefer for Thomas (@Tguntenaar) to help Carina with the community work if possible. I reached out to him to see if he would be interested in one of those tasks.

**Comment by frol** [comment]
@ailisp I see it is moved to Done, should this issue be closed?

**Comment by ailisp** [comment]
Yes good catch!
