### ISSUE TITLE
UI for access control to manage permissions

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#129]
**Problem**

Currently the permission system is not editable in the UI. You can only see who can do with which labels on UI but as an moderator you cannot change the settings.

**User Story**
As an moderator, I want to edit teams, team members and their permissions in DevHub.

**Acceptance Criteria**
- When non moderator user logs in, they cannot see or access the edit permissions page
- When moderator user logs in, there is a menu navigation item that only they can see to enter the Teams page. Non moderatos cannot see this.
- When moderator user logs in, there is a button in the Teams page, to enter edit mode
  - Moderators can add and remove restricted labels
  - Moderators can create and delete teams
  - Moderators can add member and remove member from a team
  - Moderators can specify which team can do with which restricted label

**Comment by ori-near** [comment]
@ailisp Please fill out this ticket

**Comment by Tguntenaar** [comment]
I would like to add this

**Comment by Tguntenaar** [comment]
@ori-near I have a few questions about this card. 
The smart contract allows for nesting of members and teams. 
It also allows for members have their own labels.

So my first question is does the UI need to reflect this flexibility or be more restrictive?

My guess is more restrictive could you verify this?

In that case we will only allow 2 layers: teams with members. 
And restricted labels will be team specific and not member specific

Looking at the [current team page](https://near.org/devgovgigs.near/widget/gigs-board.pages.Teams). Teams seem to have 1 label and that label always allows for editing, assign and unassign. Is that also always the case or should this be flexible in a way that a label can be or editing only. Or assign and unassign only?

If you prefer to have a call let me know.

**Comment by frol** [comment]
Well, I would like to start with that [the contract code](https://github.com/near/neardevhub-contract/blob/8dd8e5d1ba53ed30b8ef2ad1c99da2ed8e8d76a0/src/access_control/mod.rs#L49) only allows to edit moderators if the transaction is signed by the contract account id itself (`devgovgigs.near` on mainnet), so even moderators cannot invite or edit permissions at the moment.

> So my first question is does the UI need to reflect this flexibility or be more restrictive?

I vote for having _very simple UI_ for this functionality, potentially even a separate page not linked from the DevHub UI for now. As it is only useful for a couple of people on the team. The most common action is: add a new member to an existing group.

**Comment by ori-near** [comment]
Hey @Tguntenaar is this still blocked? I believe we answered your questions.

**Comment by ori-near** [comment]
@Tguntenaar Btw I updated the AC based on our discussion last time (e.g. to show the teams tab in the navigation only for admins).

**Comment by Tguntenaar** [comment]
BLOCKED
>  Moderators can specify which team can do what with which restricted label

@ori-near Are you asking whether moderators have the ability to restrict their actions to editing posts with specific labels, as well as restrict assigning and unassigning ONLY for specific labels.

Hopefully my question is clear. As of right now a moderator can specify one or multiple rules/labels for teams however these labels always give _and_ editing rights _and_ assigning rights. So my question is: should this be: **AND/OR** instead of **AND**.

**Comment by ori-near** [comment]
Hi @Tguntenaar –  believe we already resolved this blocker. What do you need to move this ticket over the finish line?
