### ISSUE TITLE
[Communities] Introduce new communities header UI

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#134]
**Problem:**
Currently, our community pages have a simple header UI with just a small icon, which prevents communities from customizing the look and feel of their page and make it inviting to engage with their members.

**User Story:**
As a community admin, I want to have the ability to customize our page in a visually engaging way so that I can reflect the unique identity of our community and engage with our members.

**Acceptance Criteria**
- Communities header UI element should reflect the attached design
  - Header image (1320px by 240px) 
  - Profile image (150px by 150px) – Use this image to update the image of the community card on the view all communities page)
  - Community title (limit character length to fit one line for the description of each community card on the view all community page)
  - Community short bio (limit character length to fit two lines for the description of each community card on the view all community page)
  - Share button that allows users to easily copy and share the URL of the community page (can use similar functionality to share [button on this page](https://near.org/near/widget/ComponentDetailsPage?src=devgovgigs.near/widget/Ideas))
  - Introduce dropdown functionality to categorize common pages such as channels (Telegram, Github)
-  User with admin permissions can customize all of the above fields in the admin page

![Image](https://github.com/near/neardevhub-widgets/assets/110252255/52b9d696-1e5b-4079-b766-307c016fc1b5)

Attachments:
- [Figma design](https://www.figma.com/file/xljqsS35U3TGkm07gTVYVv/Communities?type=design&node-id=0%3A1&t=BtEe0LrkMxhRXGQe-1)

**Comment by Tguntenaar** [comment]
@ori-near could you assign me?

**Comment by Tguntenaar** [comment]
I finished broadly, will finish up on details like font specifics once the first draft is reviewed.

**Comment by Tguntenaar** [comment]
The current banner is not the same, however I guess after @near-akaia-root is done that can be adjusted easily.

![Image](https://github.com/near/neardevhub-widgets/assets/28901891/a9a273b2-5dd2-4386-8640-77fe426ecac8)

**Comment by Tguntenaar** [comment]
And the mobile view

![Image](https://github.com/near/neardevhub-widgets/assets/28901891/5a027419-7622-4f6e-8785-aa6f5c22db55)

**Comment by near-akaia-root** [comment]
> The current banner is not the same, however I guess after @near-akaia-root is done that can be adjusted easily.
> 

Yep, it's just we don't even have banners yet and they're to introduce in updates I'm working on

**Comment by ori-near** [comment]
Thanks for the progress @Tguntenaar. Is it possible to keep the same proportions for the image in mobile view?

**Comment by Tguntenaar** [comment]
@ori-near thanks for the feedback. Will update it today so it matches the same aspect ratio.

**Comment by Tguntenaar** [comment]
@ori-near I updated it so the aspect ratio of the images stays the same. I created a PR to @near-akaia-root her fork.

![Image](https://github.com/near/neardevhub-widgets/assets/28901891/b48dd709-904f-4a7c-baa6-468867785f00)
![Image](https://github.com/near/neardevhub-widgets/assets/28901891/511b9c3b-8ff3-4767-bb7d-d664114b9aff)

**Comment by near-akaia-root** [comment]
Closed in https://github.com/near-akaia-root/neardevhub-widgets/pull/1

**Comment by near-akaia-root** [comment]
@ori-near shall I move it to done now?

**Comment by ori-near** [comment]
Looks great, thank you @Tguntenaar and @near-akaia-root. Is there a preview link to see this?

**Comment by near-akaia-root** [comment]
@ori-near https://near.org/#/root.akaia.near/widget/gigs-board.pages.community.Overview?handle=protocol&nearDevGovGigsContractAccountId=devgovgigs.near

**Comment by ailisp** [comment]
Done by @Tguntenaar
