### ISSUE TITLE
[Communities] Revamp community home page with discussion & sidebar

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#135]
**Problem**
Currently, the homepage for each community is a static page with text, which is not super engaging and interactive for users. Additionally, the separate discussion page contains valuable content but requires additional clicks.

**User Story**
As a user, I want to quickly learn about a community and see the latest activity when I land on the homepage so I can choose how to engage.

**Acceptance Criteria**
- Feed: 
  - Display a feed of posts within the community, sorted by recent activity
  - Allow users to view and engage with the posts (like, reply)
  - Users can create solution/ideas post for the community (which will automatically apply the community tag)
- Sidebar: 
  - Show community short bio text, featured links, community tag, and moderators – these fields are set by the moderator during the creation of the page
  - Allow moderators to edit the information on the sidebar by entering the edit community mode

**Design**
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/a3ca5ae3-cc50-4a08-a134-fff34ded2705)

**Attachment**
See [Figma design](https://www.figma.com/file/xljqsS35U3TGkm07gTVYVv/Communities?type=design&node-id=43%3A5756&t=wwk4uQQaVNrAvfbV-1)

**Comment by jefedeoro** [comment]
I can work on this one and get it done by Sunday.

**Comment by jefedeoro** [comment]
Blocker: 
Unsure which content exactly to load into the sidebar cards.

**Comment by jefedeoro** [comment]
Have everything ready to swap out the mock data for the actual data once that part is ready.
Please let me know if you would like any edits done to the layout.

![image](https://github.com/near/neardevhub-widgets/assets/83683076/d50f6dc3-b5b5-452b-829d-6c0b1dce752e)

**Comment by jefedeoro** [comment]
updated sorting the team members by position owner -> admin -> moderators -> members

![image](https://github.com/near/neardevhub-widgets/assets/83683076/adfd58c3-0503-40dd-83b6-8427735f7845)

**Comment by ori-near** [comment]
Hi @jefedeoro – thanks for working on this so quickly! Please take a look at the acceptance criteria line by line, as some of the requirements are missing such as not incorporating the activity/feed. Also in terms of design, the header should fit 100% on the page and underneath it the feed should take around 70% and the sidebar 30%. Also, the design looks a bit out of place – please try to follow the model from the mockup a bit more, or use the existing implementation on near.org as a reference: https://near.org/near/widget/ProfilePage?accountId=root.akaia.near. Thank you.

**Comment by jefedeoro** [comment]
![image](https://github.com/near/neardevhub-widgets/assets/83683076/03e8f09a-4a33-4f79-b1c7-fdd0d6c87ef1)

getting closer :)

couple more adjustments to make.
- tags in the sidebar
- compressing the new post launcher to the `+Post` button 
     - question on that, where will that button go? to a pop up list of post options or to a different page?
- adding .near names to the team list 
- social link labels to be social handles for that platform
     
 Please let me know if there is anything else I am missing

**Comment by jefedeoro** [comment]
Update:
Sidebar added to post feed page.
Controller bar is hidden behind a `+ Post` button. 
(css blocker can not seem to get the little circle around the + to be round it keeps squishing a little.)
moved required labels tag and made it more subtle.
doing an approx 70-30 split (mb-8 on the feed and mb-4 on the sidebar)

![Image](https://github.com/near/neardevhub-widgets/assets/83683076/22411c7f-b0d7-4928-898f-959a09307252)

I was not sure what to do with the post button so have it opening a modal with the options that were there before. 
I updated the Controller widget to match the appearance with out the border and a soft drop shadow

![Image](https://github.com/near/neardevhub-widgets/assets/83683076/285f5dbf-1c42-4c8b-b0eb-49ef1d85861c)

Next will be adding the tags then it should be ready for the full data.

**Comment by jefedeoro** [comment]
![image](https://github.com/near/neardevhub-widgets/assets/83683076/30223fdf-f203-495f-ba9c-8487d12eb1ce)

**Comment by jefedeoro** [comment]
https://near.org/jgdev.near/widget/gigs-board.pages.community.Discussions?label=zero-knowledge

**Comment by jefedeoro** [comment]
I also added the sidebar to the overview page. Plese let me know if you would like me to leave it or remove it. and if it stays would you like it added to the sponsorship and events pages?

![image](https://github.com/near/neardevhub-widgets/assets/83683076/5c2c9d2e-93ed-46a2-af91-ac276041f9bd)

**Comment by jefedeoro** [comment]
components added or edited:

pages.community.Sidebar:
just needs the data for the links and teams can be added to any page.
Currently it loads after the post feed please let me know if on mobile you would like that to load at the top, to aviod scrolling past all the posts for that info.
![image](https://github.com/near/neardevhub-widgets/assets/83683076/010f0cc5-f733-4d76-b537-76b9265c1cd2)
![image](https://github.com/near/neardevhub-widgets/assets/83683076/7d8607f8-d131-492e-a2a4-c3b071286dc6)

components.posts.DiscussionFeed:
To display as per the mockup. (removing the searchbar)
![image](https://github.com/near/neardevhub-widgets/assets/83683076/2ff1e813-1073-42eb-825e-6413ca242530)


components.layout.PlusPost:
button to replace the Controls widget above the discussions feed.
when clicked opens a modified Controls widget below.
![image](https://github.com/near/neardevhub-widgets/assets/83683076/489ba827-2691-4a6c-aacc-a8800482480e)
![image](https://github.com/near/neardevhub-widgets/assets/83683076/ac968f85-52b1-49bb-8ab8-9b3239e5bd03)

Rebuilt the components.layout.Controls widget to match the style and colors used as well made it mobile compatible down to a 250px screen 

![image](https://github.com/near/neardevhub-widgets/assets/83683076/da1024bd-756e-4d9c-a8fd-44ece036ce87)
![image](https://github.com/near/neardevhub-widgets/assets/83683076/5fbd90ee-aa49-4ec6-bc9e-3cc1a1814ae1))
![image](https://github.com/near/neardevhub-widgets/assets/83683076/a9aef68b-4ba5-446b-90d7-0b9e63e8bac1)

components.posts.Post:  as per issue #136 [136](https://github.com/near/neardevhub-widgets/issues/136)

**Comment by ori-near** [comment]
Hi @jefedeoro – thanks for working on this.

1. Post Button – please leave the existing experience that is currently shown on the [Discussions page](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.Discussions?label=zero-knowledge) (Submit Idea/Solution). When a user clicks on it, it will take them to create a new idea/solution screen with the label prefilled. We do not need to expose all of these 4 options.
2. "I also added the sidebar to the overview page" – no need to add the sidebar to the other page. Just the homepage/activity.

Please let me know if you have any additional questions.

**Comment by ori-near** [comment]
@ailisp We need to assign someone else to this ticket. Perhaps @Tguntenaar would be interested, since he worked on the header?

**Comment by Tguntenaar** [comment]
@ori-near I am, if you could assign me will do it this week

**Comment by near-akaia-root** [comment]
Closes #194

**Comment by Tguntenaar** [comment]
@ori-near I created a PR for #135 and #136
