### ISSUE TITLE
[Communities] Improve post UI look

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#136]
As a user, I want a a clean and soft user interface for posting on DevHub so that it's easier on the eyes.

**Acceptance Criteria**

- The border color of the post UI should change to a softer gray to reduce sharpness and create a more visual experience 
- Adjust the font size and style for readability per the design
- Increase the spacing between paragraphs and lines to improve the readability
- Add visual distinction to highlight the author's information
- Move the labels lower on the post and make them less prominent to put the emphasis on the content
- Make the read more less distracting

Current state:
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/568e44a3-492e-416b-a604-42871f70856c)

See suggested improvements: 
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/cfcbea16-66b4-4bbc-8adf-3c319c666ad1)

Notes: Please refer to the post experience on https://near.social/ and near.org for potential ideas.

**Comment by jefedeoro** [comment]
I can work on this one and will have it completed by Sunday at the latest.

**Comment by jefedeoro** [comment]
I am going to start working on this one as well. 
@ori-near can you please move this to in progress?

**Comment by jefedeoro** [comment]
![image](https://github.com/near/neardevhub-widgets/assets/83683076/a4f67c16-5d09-4a03-991c-83702bf74b27)

![image](https://github.com/near/neardevhub-widgets/assets/83683076/6f3007af-8109-48b1-a6dd-c62324592c4e)

wip but is coming along.
need to do some fine tuning for the other pages. It will be completed by Friday.

**Comment by jefedeoro** [comment]
Update:

Just needs the new profile Avatar widget and it should be ready.

-removed border
-added dropshadow
-moved labels to the bottom
-See More... button I put it on the right side, I ws feeling on a small device it was a little close to the tags and links. on the left. (please let me know if you would like it updated to be on the left.)
-adjusted buttonfooter to be more subtle
-adjust date/time to be more subtle

closed with see more example:

![Image](https://github.com/near/neardevhub-widgets/assets/83683076/565fa0b3-814c-4d0c-b62a-1abcb4c41364)

and here it is expanded with the close button visible:

![Image](https://github.com/near/neardevhub-widgets/assets/83683076/659ee3e9-1b3a-4372-b3da-f069361fe437)

and a threaded post example:

![Image](https://github.com/near/neardevhub-widgets/assets/83683076/8a73104f-24b6-4153-9055-4d8fff12ce2d)

**Comment by jefedeoro** [comment]
![image](https://github.com/near/neardevhub-widgets/assets/83683076/9b033f83-21c5-49e2-aada-ebccc2d8f1e0)

near.org/jgdev.near/widget/gigs-board.components.posts.Post

**Comment by jefedeoro** [comment]
I am having a challenge to find where to inject the new link styling. any pointers would be appreciated.

**Comment by jefedeoro** [comment]
I also made it more dynamic for mobile:
old mobile view:
![image](https://github.com/near/neardevhub-widgets/assets/83683076/0f08a7b9-9de0-48e7-819b-372e19737b2d)


current mobile view:
![image](https://github.com/near/neardevhub-widgets/assets/83683076/662e325f-c22e-449f-aff9-9f1969630b9d)

**Comment by jefedeoro** [comment]
some fine tuning on the spacing and the font and image sizing and weights
Just have the link color left to figure out o this issue.
Please let me know if there is anything I am missing.

changes 

How it loads on the main page:
![image](https://github.com/near/neardevhub-widgets/assets/83683076/bbca839f-6596-4932-9c08-5d189562f706)

How it loads in the discussions page with the sidebar:
![image](https://github.com/near/neardevhub-widgets/assets/83683076/af5fe260-25a0-455a-b28b-240cf0032126)

and how it looks on mobile
![image](https://github.com/near/neardevhub-widgets/assets/83683076/c8580c61-ab2c-492a-b019-132e37e76322)

tablet:
![image](https://github.com/near/neardevhub-widgets/assets/83683076/3a2b955a-a5ab-4911-8f55-5691ad9e2735)

**Comment by ori-near** [comment]
@ailisp We need to assign someone else to this ticket. Perhaps @Tguntenaar would be interested, since he worked on the header?

**Comment by Tguntenaar** [comment]
@ori-near I can pick it up

**Comment by Tguntenaar** [comment]
Still a work in progress but would love to get some feedback on the sidebar. I differs quite a bit from the figma design. What do you think about the tiles @ori-near? Please note I'm not finished.

![Image](https://github.com/near/neardevhub-widgets/assets/28901891/7e8afe2f-5d8c-4a14-91fd-6eebe2984b77)

**Comment by ori-near** [comment]
Hey @Tguntenaar – sorry for my delay, just returned from a week off. I think this direction is fine for now, we can polish it later. But please just make sure to better align things. For example, the telegram icon in the about section should left align with the label and text above it. Also, the border rounding should be consistent as the post type (I prefer the smaller radius one). Let me know if you have any other questions.

**Comment by Tguntenaar** [comment]
Alright! Will finish this today and create the PR for #135 as well
