### ISSUE TITLE
Create section hiding children in small screens (hidden items: Idea  Solution  Attestation  Sponsorship)

### ISSUE THREAD

**Issue by jefedeoro** [near/neardevhub-widgets#138]
**Describe the bug**
UI bug on create section of the header. when going to smaller screens ( below 992 px width ) the options to select create type are not visible on the page.

**To Reproduce**
1. Go to '[...](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Feed)'
2. Change screen size smaller
3. Scroll down to 'top'
4. See error on the `Create` section of the page, in the smaller size the options for creation type are not visible.

**Expected behavior**
As shrinking either go to a popup menu when clicking `Create` (currently non responsive), or make the create type links smaller or turn to just the icons with tooltips when hovering with the title for each link. 

**Screenshots**
![Screenshot 2023-05-28 113746](https://github.com/near/neardevhub-widgets/assets/83683076/000db742-7229-4554-b682-6743ef8fb5a0)

![Screenshot 2023-05-28 113802](https://github.com/near/neardevhub-widgets/assets/83683076/165c5c4a-d735-44c0-8fee-d17a74643c90)

![image](https://github.com/near/neardevhub-widgets/assets/83683076/de8fdcff-a9f1-4eac-a809-6d1cf44e3dbe)

**Desktop (please complete the following information):**
 - OS: [w11]
 - Browser [chrome, edge]
 - Version [>111]

**Comment by ailisp** [comment]
It's not an issue now as create new post jump to a new page and I tested it works fine on mobile size screen
