### ISSUE TITLE
Create solution post & solution reply are different 

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#142]
With the recent launch of the new post creation UX (https://github.com/near/neardevhub-widgets/issues/20), currently the fields for the create solution are different from the reply solution This leads to an inconsistent UI and user experience. For example, right now a user is required to select the currency from a dropdown in the Solution post, which includes the option for USDC. However, the Solution reply only exposes a field, and a user gets a warning when they enter USDC.

**To Reproduce**
1. Go to DevHub
2. Click on Submit Idea / Solution, then Solution
3. User sees the following fields:
  - Title (text field)
  - Description (large text field)
  - Labels (type dropdown)
  - Are you seeking funding? (Radio button yes or no)
  - When user selects yes, they see:
    - Currency (dropdown with three options: NEAR, USDC, USD)
    - Requested amount (number only text field)
    - Requested sponsor (text field)
4. Navigates to any existing post on the feed and click Reply, then Solution
5. User sees the following fields, which are different for the ones shown in step 3:
    - Labels (type dropdown)
    - Title (text field)
    - Description (large text field)

**Expected behavior**
- User should see the same fields & preview in the solution reply as shown in the create solution post
- User should be able to select USDC and proceed successfully without a warning message

**Screenshots**
<img width="1580" alt="Screenshot 2023-05-30 at 3 15 59 PM" src="https://github.com/near/neardevhub-widgets/assets/110252255/fb2327f5-f13c-48c2-ace1-d48dafe68061">

**Comment by Tguntenaar** [comment]
I would like to tackle this

**Comment by near-akaia-root** [comment]
Assigned @Tguntenaar

**Comment by Tguntenaar** [comment]
Currently in progress

**Comment by Tguntenaar** [comment]
I've finished the solution however it shows some weird behaviour rendering the input fields multiple times on state change. Still have to work on that before I make a PR. Also waiting @ori-near his reply what to do with the sponsorship option.

**Comment by Tguntenaar** [comment]
> Hi @Tguntenaar – I believe we already discussed this on our call a couple of weeks ago. Please let me know if you're still blocked.

Not blocked! Created a PR for it yesterday as well.

**Comment by ori-near** [comment]
Hi @Tguntenaar – I see that we closed this ticket – but I still see the bug where the solution reply is not the same as the solution create. Do we need to reopen this?

CC: @ailisp

**Comment by ailisp** [comment]
> Do we need to reopen this?

Yes

**Comment by ori-near** [comment]
Hi @Tguntenaar – just checking in on this ticket, as it is been open for a while. What do we need to do to move this over the finish line?

CC: @ailisp

**Comment by Tguntenaar** [comment]
Hello, @ailisp and @ori-near! PR #215 addresses this particular issue, and I've just submitted it for review. Upon further examination, I noticed it was linked to the earlier PR #205, which has already been merged. This linkage may have led to my initial confusion, as I glanced at it too briefly and mistakenly assumed it was already completed.
