### ISSUE TITLE
[Communities] GitHub board is not fetching closed PRs

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#143]
**Problem:**
Since launching the new GitHub integration, the Kanban board is only fetching open PRs. However, we need to fetch closed PRs in order to show all the statuses.

**Acceptance Criteria**
- When a user configures the GitHub board to pull PRs, it should pull both open & closed PRs from GitHub

**Comment by near-akaia-root** [comment]
UPD: in review
