### ISSUE TITLE
UI for Permissioning for Adding Github Project Board

### ISSUE THREAD

**Issue by codingshot** [near/neardevhub-widgets#145]
**Is your feature request related to a problem? Please describe.**
Cannot create github project board, unclear if this is permissioning issue
**Describe the solution you'd like**
Would like creating a project board on Github to say "You are not part of this role, you do not have permission to add a Github project board" or something along this line
**Describe alternatives you've considered**
Error message upon submit, or grayed out submit, you do not have permission, ask a DevDAO moderator. Or list who has permission to update it

**Comment by ailisp** [comment]
I can confirm it's fixed. If you do not have permission to configure a github board, it will not show configuration button so you won't hit this problem
