### ISSUE TITLE
Order Telegram Messages from Most Recent to Oldest

### ISSUE THREAD

**Issue by codingshot** [near/neardevhub-widgets#146]
**Is your feature request related to a problem? Please describe.**
Currently to see the latest telegram message you need to scroll all the way down this is counterintutive.

**Describe the solution you'd like**
Reverse order the messages from most recent to latest. Additionally if there was a way to load older messages to scroll down.

**Comment by ailisp** [comment]
@ori-near @frol What do you think?

**Comment by ori-near** [comment]
It is a valid point. @ailisp Could we easily add a Sort by oldest or newest button, with the default setting sort by newest selected?

**Comment by ailisp** [comment]
Discussed in meeting, our consensus is newest first for now (same as @codingshot proposed)
