### ISSUE TITLE
Clicking on User Telegram and Group link Leads to Iframe Error

### ISSUE THREAD

**Issue by codingshot** [near/neardevhub-widgets#147]
**Describe the bug**
When clicking a link within telegram embedd their is an error

**To Reproduce**
1. Go to https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.Telegram?label=tooling
2. Click on a profile name, the tg topic name, the telegram icon
3. See error
<img width="746" alt="Telegram Embedd Error" src="https://github.com/near/neardevhub-widgets/assets/45281667/e939c411-e755-4f95-ae79-ba1802015e29">

**Expected behavior**
Would like this to open in new tab to see the group or see user account.
**Screenshots**

**Desktop (please complete the following information):**
- Brave Browser

**Comment by ori-near** [comment]
Hi @codingshot – thanks for filing this. Are you still seeing this error? I just checked on my end and unable to reproduce this:

![Screenshot 2023-06-05 at 3 30 21 PM](https://github.com/near/neardevhub-widgets/assets/110252255/8f808ab3-516d-4098-9a6a-b40474837661)
