### ISSUE TITLE
Solution post preview should still show funding currency & amount if requested sponsor is empty

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#150]
**Describe the bug**
With the recent launch of the new post creation UX (https://github.com/near/neardevhub-widgets/issues/20), when a user seeks funding but does not specify the optional requested sponsor field, the preview/post do not show the currency and requested amount. This means that no sponsorship information is displayed, making it hard for DAOs to know how much was asked for.

**To Reproduce**
1. Go to DevHub
2. Click on Submit Idea / Solution, then Solution
3. Select Yes for "Are you seeking funding for your solution"
  - Select NEAR for "Currency"
  - Enter 20 for "Requested Amount"
  - Leave requested sponsor empty
4. Preview does not show 20 NEAR

![Screenshot 2023-06-07 at 3 26 18 PM](https://github.com/near/neardevhub-widgets/assets/110252255/3db57d4f-cf63-46b2-86b7-bab0bde53c7c)

**Expected behavior**
Preview should still show the 20 NEAR, even if the requested sponsor field is empty.
![Screenshot 2023-06-07 at 3 27 21 PM](https://github.com/near/neardevhub-widgets/assets/110252255/feb8bf94-bbd2-419f-bf36-582bb57e9164)

**Additional context**

**Comment by sumitshinde-84** [comment]
i would like to work on this issue , can you please assign it to me?

**Comment by ori-near** [comment]
Hi @sumitshinde-84 –  thanks so much for expressing interest 🔥. We appreciate your willingness to contribute!

We have assigned this ticket to you and would like to kindly request that you submit a pull request with your solution within one week. If you are no longer able to work on this issue, please let us know so we can reopen it for another developer to take on. 

Please refer to our [contribution guidelines]( https://github.com/near/neardevhub-widgets/blob/main/CONTRIBUTING.md) and [how we work](https://github.com/near/neardevhub-widgets/blob/main/docs/how-we-work.md) for some helpful resources on contribution to our project.

Once again, thanks so much and we look forward to your contribution.

**Comment by ori-near** [comment]
Hi @sumitshinde-84 – how's it going? Are you still working on this ticket? Please confirm if you can submit your pull request this week or if we need to un-assign you from this ticket. Thank you.

**Comment by ori-near** [comment]
Given that we haven't received a response for a month, we unassigned this ticket and moved it to the backlog. Anyone is welcome to grab it.

**Comment by elliotBraem** [comment]
I can pick this one up @ori-near

**Comment by Rishabhraghwendra18** [comment]
Hi @ori-near, is this issue still open?

**Comment by ori-near** [comment]
Hi @Rishabhraghwendra18 – thank you for checking. It was fixed.
