### ISSUE TITLE
[Communities] Improve Telegram configurations

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#157]
- Page improvements 
  - Sort by newest first (since it's not intuitive and we want the views to refresh for users)
  - Make links work
  - Add "Recent posts" Title
  - Add button to view more posts to take you to Telegram channel- 

- Customization
  - Add ability to add more than one channel

**Comment by ailisp** [comment]
Make links work isn't possible due to VM limitation. I made a pull request there: https://github.com/NearSocial/VM/pull/92

**Comment by ailisp** [comment]
> Add ability to add more than one channel

Require a contract change, I'll make a PR there and go back.
