### ISSUE TITLE
[Communities] Improve GitHub configurations

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#158]
- [x] Enable issues in addition to PRs.
- [x] Increase # of columns.
- [ ] Customize card fields.

**Comment by near-akaia-root** [comment]
@ori-near

1. What's the new maximum number of columns?
2. Please elaborate on card fields customization

**Comment by ori-near** [comment]
@near-akaia-root 
1. What do you think is a reasonable number to set? Please make a call here.
2. I mean the ability to customize which fields may show on the card itself. Similar to how GitHub does this for boards: ![Screenshot 2023-06-16 at 1 12 11 PM](https://github.com/near/neardevhub-widgets/assets/110252255/562f8053-4efc-44e9-b971-b5ecc42380f1)

**Comment by near-akaia-root** [comment]
@ori-near 

1. I think 20 will be more than enough for everyone
2. Got it!

**Comment by ailisp** [comment]
Looks like only "Customize card fields" is left

**Comment by carina-akaia** [comment]
Subtask 3 in moved to #250

**Comment by ori-near** [comment]
Thanks for moving this to a separate ticket @carina-akaia.
