### ISSUE TITLE
Telegram tab should be hidden if community doesn't have a telegram configured

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#169]
**Problem**
Telegram - if nothing was entered in create/edit community, it shows error message on Telegram tab

**Acceptance Criteria**
Need to hide telegram tab if community has no telegram configured

**Comment by Tguntenaar** [comment]
Looking at entity.community.header. It seems like this is already fixed. This should be closed

**Comment by near-akaia-root** [comment]
@Tguntenaar there's a catch if you save telegram_handle as an empty string. I'll fix it.
