### ISSUE TITLE
[Communities] Implement form validation

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#172]
**Problem**
Currently, a user is able to submit various inputs that are not allowed due to a lack of front end validation. This may result in error messages and poor user experience.

**User Story**
As a user interacting with the various forms on DevHub, I want to know in-real time if I am entering fields that are not allowed, so that I can have a smooth and error-free user experience once I click submit/next etc.

**Acceptance Criteria**

On the community create page:
- For all required fields (e.g. Name, Description, Handle, Tag, Admins) – a user should not be allowed to continue without filling them out. Also make the bio field under about required (add a red * next to Bio) and apply the same required behavior.
- For all fields with a maximum length requirement, form should prevent user from typing more characters. For example, for the Twitter Handle field, a user should not be allowed to enter more than the maximum 60 character limit limit.
- For URL handle and tag, do not allow commas or spaces.
- The website field show only allow to paste a valid URL
- If a user sets a name for wiki page, they must not leave content blank

**Comment by ori-near** [comment]
Hi @ailisp Can you please re-esimate this ticket? And let me know if I should break this into two tickets (e.g. one for form validation, the other for improving the page access control)? Thank you.

**Comment by ailisp** [comment]
@ori-near a week's estimate should be a safe upperbound. 
> Improve the UI experience for entering additional admins (see options below)

takes at most 3 days and remaining tasks should take at most 2 days

**Comment by ori-near** [comment]
Hi @ailisp – thanks so much! I ended up splitting the https://github.com/near/neardevhub-widgets/issues/241 into a separate story since they seem parallelizable.

**Comment by espensimensen** [comment]
@ori-near I can look into this ticket
