### ISSUE TITLE
[Communities] Improve the About form fields for create/edit page & corresponding sidebar rendering

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#173]
**Problem**
Currently, when a user creates a new community, the About section fields that populate the community sidebar are not intuitive. For example, "Twitter handle" does not make it clear to the user whether they should enter @twitterhandle, twitterhandle, www.twitter.com/handle, or https://www.twitter.com, etc. This may lead to errors and a poor UX. Also the sidebar rendering for links has some issues such as displaying super long links that wrap, showing prefixes, and opening links in the same window which takes users away from the community page.

![Image](https://github.com/near/neardevhub-widgets/assets/110252255/11d79d50-abb8-4763-9ad9-f289cba55151)

**User Story** 
As a user, I want to clearly understand what form inputs are expected so that I can easily create a community without having to guess what is expected and/or get error messages.  

**Acceptance Criteria**

**Community create/edit page:**
- The bio field should not contain a resize button at the bottom right corner of the text area, given that only 200 characters are required. The bio field should be large enough to display up to the allowed 200 characters.
- Change the following form labels: "Twitter handle" to "Twitter", "GitHub organization handle" to "Github" to reflect the attached designs
- Add a prefix to each form field to reflect the attached designs, also see [near.org profile page](https://near.org/near/widget/ProfileEditor) example.
  - Twitter prefix should say: "https://twitter.com" 
  - GitHub prefix should say:  "https://github.com/" 
  - Telegram prefix should say: "https://t/me/" 
  - Website prefix should say: "https://"

**Community homepage sidebar about section**
- Each link in the community sidebar should open in a new window. 
- Each link in the community sidebar should display the text that was entered without the prefix. For example, after the website "https://" prefix if a user entered "near.org" the sidebar should just show near.org" 
- Each link in the community sidebar should fit within the sidebar. So if a user enters a super long url beyond the width of the sidebar, the url should shorten and have three dots in the end of one line. For example, instead of displaying "www.google.com/super-long-text" display "www.google.com/super-lon..."

Important Note: As of August 11, 2023, the Telegram handles field in the About section populates both the sidebar link section as well as the Telegram tab. However, @carina-akaia is working to create a separate section in the community create/edit page to enable the Telegram Tab (see https://github.com/near/neardevhub-widgets/issues/175). We should add a separate field to allow multiple Telegram handles. And keep only one Telegram field for the sidebar. 

**Design Reference**
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/2820b157-345a-4fcc-b9fd-5a7ebccc0428)

**Comment by carina-akaia** [comment]
Regarding the Bio ( as well as wiki ), there's a related ticket: #238

**Comment by ori-near** [comment]
Thanks @carina-akaia! Ok, we can update this ticket after https://github.com/near/neardevhub-widgets/issues/178 is complete. I also just expanded the scope of this ticket to address the actual rendering of links on the sidebar.

**Comment by elliotBraem** [comment]
I can pick this one up

**Comment by elliotBraem** [comment]
I don't understand the telegram comment here -- I understand we will want something like described [here](https://github.com/near/neardevhub-widgets/issues/241), but I don't know if I'm supposed to implement as part of the story.

I've added the prefix, but I've left the comma-separated multi-telegram functionality because this is how it is saved in the contract, as an array of handles.

**Comment by ori-near** [comment]
Hi @elliotBraem – just wanted to follow up here. As we discussed on our call last week, currently the Telegram field in the About section has two functions: 1) Displays Telegram link(s) in the about section; 2) Enables Telegram widget/tab. We will separate these two functions in https://github.com/near/neardevhub-widgets/issues/175. 

Please confirm what you need to move this story over the finish line.

**Comment by elliotBraem** [comment]
This PR is ready for review. The only thing that was holding me back was whether or not it should support one or multiple telegrams -- I have made necessary changes but I still allow multiple comma-separated telegrams here. @ori-near @ailisp

**Comment by ailisp** [comment]
> This PR is ready for review. The only thing that was holding me back was whether or not it should support one or multiple telegrams -- I have made necessary changes but I still allow multiple comma-separated telegrams here. @ori-near @ailisp

I see. @ori-near What is your opinion on the design of the textbox for input telegram handles?
