### ISSUE TITLE
[Communities] Give DevHub moderators the ability to set Featured Communities on homepage

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#176]
**Blocked by** https://github.com/near/neardevhub-contract/issues/36

**Problem**
Currently featured community is hard coded. We would like moderators to configure which communities are featured community. This info is stored and retrieved in smart contract.

**Acceptance Criteria**
- Featured communities are retrieved by view call contract's list_featured_communities method
- Only for moderators, show an edit Featured community button beside featured community, which directs the user to a simple form with one text input. The content of the input are the handles of featured communities. Save this should call smart contract to set featured communities.

**Comment by jaswinder6991** [comment]
I want to work on this. I have also looked into the blocker Contract issue too. I can work on both.

**Comment by jaswinder6991** [comment]
Hi @ailisp
This issue was blocked by https://github.com/near/neardevhub-contract/issues/36 which was addressed using this PR https://github.com/near/neardevhub-contract/pull/42

For the front end widget to include the featured community code, here is the fork with needed changes.

https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=contract.devhubopen.testnet&nearDevGovGigsWidgetsAccountId=devhubopen.testnet

**Comment by ori-near** [comment]
Hi @jaswinder6991 – thanks so much for all your work here, we really appreciate it. Just to clarify, is this ticket (#176) still blocked? Or is it now ready for anyone to pick up?

**Comment by jaswinder6991** [comment]
> Hi @jaswinder6991 – thanks so much for all your work here, we really appreciate it. Just to clarify, is this ticket (#176) still blocked? Or is it now ready for anyone to pick up?

Hi @ori-near, the contract changes are done and deployed. A moderator will still have to call set_featured_communities function in the contract. For the front end changes, you just have to checkout what I did here and use that, it is just a few lines. 
https://test.near.org/devhubopen.testnet/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=contract.devhubopen.testnet&nearDevGovGigsWidgetsAccountId=devhubopen.testnet

**Comment by ailisp** [comment]
Hi @jaswinder6991 Sounds good! Could you please make a pull request for frontend?

**Comment by jaswinder6991** [comment]
Hi @ailisp, created a PR here - https://github.com/near/neardevhub-widgets/pull/242

**Comment by ori-near** [comment]
Hi @jaswinder6991 – is this ticket still in progress? What do we need to do to move it over the finish line?
