### ISSUE TITLE
[Communities] Reuse the Markdown component instead of plain multiline textbox for edit community wiki

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#178]
**Problem**
Currently it's a plain multiline text box to edit community wiki, such as event or overview, which is not very intuitive.

**Acceptance Criteria**
Reuse the same Markdown component used by write post widget, to edit and real-time preview the wiki

**Comment by elliotBraem** [comment]
Good catch @carina-akaia.

This can be assigned to me and moved to in-progress. I’ll cover it in my other PR. @ori-near

**Comment by elliotBraem** [comment]
This is on pause due to the scope change for communities.

**Comment by elliotBraem** [comment]
Blocked until #255 and #245 are merged

**Comment by ori-near** [comment]
Hi @elliotBraem – can we move this back to In Progress or Backlog given that #255 and #245 are now merged?

**Comment by elliotBraem** [comment]
Yes, will finish this up today.
