### ISSUE TITLE
Any update on wiki1/wiki2 is not being applied

### ISSUE THREAD

**Issue by walnut-the-cat** [near/neardevhub-widgets#183]
**Describe the bug**
it seems my edit attempts on wiki1/wiki2 are failing. When I edit contents, the preview shows all the changes I made, but once I click save, the loaded page doesn't include any of the changes I made. When I checked the txn submitted, it says successful, but the arguments show the empty body, meaning my changes are for some reason gone missing while submitting txn.
https://explorer.mainnet.near.org/transactions/EzLBVm8ejGDEXhNe3JQBZUr5kwk7CDvTu6Md3YnPmq9C

**To Reproduce**
1. Go to Community Protocol group page
2. Click Edit to update contents
3. Make some changes to Wiki1 or wiki2 (e.g. set title and content to 'test')
4. Submit changes
5. Observe the changes are not being applied

**Expected behavior**
Whatever title/content changes on wiki1/wiki2 should be applied

**Screenshots**
https://drive.google.com/file/d/1VmzQUn5CX4NGa1ISQGh-LpHz2iEe26G6/view?usp=sharing

**Desktop (please complete the following information):**
 - MacOS Ventura 13.1
 - Chrome Version 114.0.5735.106 (Official Build) (arm64)

**Additional context**

**Comment by walnut-the-cat** [comment]
I want to say that this issue seems to be quite critical, as there is no real way for me to either 1) update any contents or 2) bring back the previous/original contents, at least from UI.

**Comment by walnut-the-cat** [comment]
Additional information.

Txn preview window does not contain the changes made in wiki pages as can be seen in the screenshot.
<img width="791" alt="Screenshot 2023-06-21 at 1 05 57 PM" src="https://github.com/near/neardevhub-widgets/assets/122475853/b4417c4e-2b52-4d0b-9f20-d0af2b7152d2">
<img width="903" alt="Screenshot 2023-06-21 at 1 06 01 PM" src="https://github.com/near/neardevhub-widgets/assets/122475853/4d3226c3-8c78-4289-b430-2cf02de40e83">

**Comment by near-akaia-root** [comment]
@walnut-the-cat fix is on the way in #187

**Comment by walnut-the-cat** [comment]
Don't think the issue is fixed. It shows the content in the preview, but once I submit the transaction, the change is still not reflected

**Comment by frol** [comment]
@walnut-the-cat Can you record a screencast? (I can recommend https://loom.com/ to make it really easy)

**Comment by walnut-the-cat** [comment]
sure. will do that soon

**Comment by walnut-the-cat** [comment]
Meteor wallet issue
* After submitting a transaction, there is no confirmation of whatsoever and the page does not refresh. 

But the txn actually goes through and I can see the updated content if I manually trigger refresh.

Here is the video showing the issue: https://drive.google.com/file/d/16osDiE0522RgUgXsreKLmoKlwlkpOrwT/view?usp=sharing

**Comment by walnut-the-cat** [comment]
The issue where Near wallet bails out with 400

When contents of community page get too long, 400 is thrown while applying changes.

According to @frol , HTTP 400 is the NEAR Wallet limitation, the GET request gets too big and the suggestion is to use other wallet.

Here is the video recording: https://drive.google.com/file/d/1fSu3EqsSpoa4pk76TlQIrJsNMr_uTJog/view?usp=sharing

I tried with Meteor wallet and thankfully it went through, so we are good, but this is not sustainable solution and we need to figure out to lift this limitation.

**Comment by frol** [comment]
Meteor Wallet updates are recorded just fine:

* https://explorer.near.org/transactions/DTjrMsrrGL6soMnJY7EdJm3Sw3hEbXbHuaxvJaNgWgvS
* https://explorer.near.org/transactions/4NXnWLvTa7JZqsReUZhzJdyxRcSR57aoJNz8L97Dbaw6

Here is the page with "test 234" on it: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.wiki?handle=protocol&id=2

There is clearly a refresh delay which is not resolved yet, so you need to refresh the page 3-10 seconds later to see the latest changes.

**Comment by frol** [comment]
> I tried with Meteor wallet and thankfully it went through, so we are good, but this is not sustainable solution and we need to figure out to lift this limitation.

NEAR Wallet is ending its life, so I doubt that anyone will bother fixing it. It is on their side and it has nothing to do with DevHub.

**Comment by near-akaia-root** [comment]
@walnut-the-cat editor state actualization fix is already WIP in #174

**Comment by ori-near** [comment]
Hi @walnut-the-cat – we closed this ticket. Can you please confirm if the issue was resolved? Please let us know if you still see any problems.
