### ISSUE TITLE
Was Able to Generate A Community Without handle now I can't edit it but it shows up on Search

### ISSUE THREAD

**Issue by nearbuild** [near/neardevhub-widgets#184]
**Describe the bug**
Created a community and https://explorer.mainnet.near.org/transactions/9xDZThM287v2kvqEvvM2HrSTG7DWPwSerL6h2yeWwVQ6 it went through but for some reason handle left out
**To Reproduce**
1. Created community
2. somewhere along the way I logged in with different account on near.social gateway
**Expected behavior**
- You must put a Community handle to continue
- OR able to edit Community you are admin for (admin dashboard)
- Able to view the DAO
- Communities page omit any communities without handle

**Screenshots**
If applicab
<img width="800" alt="DevHub Community Error" src="https://github.com/near/neardevhub-widgets/assets/106683565/bbc4a3a1-6e9a-45b7-86ce-51569fec0a2f">

**Desktop (please complete the following information):**
- MACOS Desktop

**Comment by near-akaia-root** [comment]
Correction: the community was created with a handle, but then the handle updated to an empty string ( same for the tag )
