### ISSUE TITLE
Error Check for Charter Max on Community Creation

### ISSUE THREAD

**Issue by nearbuild** [near/neardevhub-widgets#185]
**Describe the bug**
Tried to create a longer profile, but didn't realize it was over the max char length until after I was singing transaction, then i lost progress
**To Reproduce**
1. Create Community
2. Enter a description thats too long

**Expected behavior**
- On front end; you are above the character count

**Comment by nearbuild** [comment]
Well it does let you know actually, on submit button a popup would be nice to prevent this

**Comment by near-akaia-root** [comment]
There's no validation on frontend yet, will be fixed in #172
