### ISSUE TITLE
Voting poll on NEAR SOCIAL

### ISSUE THREAD

**Issue by Makeno64** [near/neardevhub-widgets#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Makeno64** [comment]
How can I implement voting poll widget on near social

**Comment by ailisp** [comment]
Duplicated with #155 . Also if you considering to implement a poll widget on NEAR Social, here is a better place to discuss: https://t.me/NEARisBOS
