### ISSUE TITLE
[Landing Page UX] Smarter ordering of posts to surface relevant content

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#19]
**Problem**
Our platform currently does not prioritize the most relevant and engaging content, which makes it difficult for users to discover high-quality posts and stay engaged. This ticket introduces a smarter ordering system for posts on the platform. 

**User Story**
As a user, I want to easily discover the most engaging and relevant posts, so that I can stay up-to-date and participate in discussions without sifting through irrelevant or low-quality content.

**Acceptance Criteria**
- Introduce three tab filters on the homepage: Top, Recent, Unanswered, that allows users to sort posts based on different criteria
- The top filter should be the default selection and prioritize posts based on engagement (e.g replies, likes, views) and recency using a simple heuristics algorithm similar to Reddit or other platforms. The algorithm should prioritize recent posts over more stale active posts
- The recent filter should order posts by creation date
- The unanswered filter should display posts with no replies, sorted by creation date
- Ensure that the new filters are performant and do not impact page load or performance

**Note**
- This idea was featured as a bounty at the [ETH Denver Hackathon](https://www.ethdenver.com)

**Comment by ailisp** [comment]
This one is implemented as part of this team's submission: https://near.social/#/devgovgigs.near/widget/gigs-board.pages.Post?id=288

**Comment by ori-near** [comment]
Hi @nearmax – You mentioned the need for "smarter" ordering of posts. Can you please review this ticket and make any changes or provide feedback to ensure this captures your intention?

**Comment by ori-near** [comment]
@ailisp Estimates around 1-5 days of work, depending on whether the hackathon solution fully meet our acceptance criteria and production board needs. He will update the size and target end date once he get gets more information.

**Comment by ori-near** [comment]
This is not as acute of a problem as before since we recently introduced the search and communities. We can incorporate the hackathon widget.
