### ISSUE TITLE
More than two wiki tabs

### ISSUE THREAD

**Issue by walnut-the-cat** [near/neardevhub-widgets#192]
**Is your feature request related to a problem? Please describe.**
Total of two wikis limits our ability to organize things in the way we are hoping for

**Describe the solution you'd like**
It will be great if there are more than two wikis supported. I don't expect infinite numbers, but 4-5 customizable wiki tabs will be nice

**Describe alternatives you've considered**
I ended up shoving things into two available wiki tabs for now

**Additional context**

**Comment by jaswinder6991** [comment]
With the new community addon framework, you can add custom widget as tabs to your community page. This included adding more wiki tabs as well.
