### ISSUE TITLE
Github tab board configuration does not work well with certain labels

### ISSUE THREAD

**Issue by walnut-the-cat** [near/neardevhub-widgets#195]
**Describe the bug**
While configuring Github tab with NEPs github repo, if S-rejected or S-retracted is used as Search term, it does not display all applicable PRs.

**To Reproduce**
1. Go to https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.github?handle=protocol
2. Click on Configure
3. Scroll down to REJECTED section
4. See REJECTED column does not show any PRs, while there are two 'rejected issues' that can be seen on Github project page: https://github.com/orgs/near/projects/51/views/1?filterQuery=label%3A%22S-rejected%22+label%3A%22WG-protocol%22
5. Try remove the label WG-protocol from REJECTED column. That should show all REJECTED issues regardless of working group, but it only shows issues for WG-contract-standards

**Expected behavior**
Github tab should properly reflect what's available on Github repo

**Screenshots**
Will be attached as comment

**Desktop (please complete the following information):**
Mac with Chrome/Firefox

**Comment by ori-near** [comment]
Hi @walnut-the-cat – thank you for submitting this. We are currently working on #158, which should resolve this. Stay tuned.

**Comment by near-akaia-root** [comment]
The patch is on the way. I also unlocked the Issue ticket type.
