### ISSUE TITLE
Only allow USDT (default) or NEAR for solution funding requests

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#198]
These days, DevHub can only provide funding in USDT or NEAR, so let's update the Solution funding request form with USDT (default) and NEAR.

Other notes:
* bridged USDC is also available, but it is more cumbersome
* fiat USD / EUR / CHF are available for very limited cases

**Acceptance Criteria**
- New solution and sponsorship posts can only use USDT or NEAR in the currency dropdown menu
- Old posts can still retroactively display the currency that was entered when they were created
- There is no error messages when creating solution or sponsorship using either USDT or NEAR

**Technical Notes** (Talk to Bo if you have questions)
- Need to change smart contract to introduce USDT
- Currency should not be removed from smart contract
- Old currencies should not be accepted by add post in smart contract

**Comment by near-akaia-root** [comment]
@frol could you please elaborate on issues with USDC.e?

**Comment by frol** [comment]
@carina-akaia The legal team does not hold USDC.e and waiting for native USDC to arrive to avoid people getting confused.

**Comment by ori-near** [comment]
Hi @frol – thanks for creating this ticket. I agree that we should simplify the solution funding options. Let's do USDT (Default) and NEAR. Note – right now there's a bug that won't even allow me to select the existing USDC option ... so whoever works on this ticket should make sure that both currency options are supported.

**Comment by elliotBraem** [comment]
I can pick this one up @ori-near

**Comment by elliotBraem** [comment]
@ori-near I've opened a PR ready for review: #222

**Comment by ori-near** [comment]
@elliotBraem Looks great! Thanks so much for linking to the [test cases](https://github.com/near/neardevhub-widgets/pull/222#issuecomment-1668679358) of the AC too. Super helpful.
