### ISSUE TITLE
[Create Post] Simplify create experience UI

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#20]
**Problem**
Currently, the create experience UI presents too many options to the user (e.g. idea, solution, attestation, sponsorship) without a clear explanation of what each post type means. It is also unclear for users to what to expect as a next step after they create a post, especially if the post is no longer at the top of the feed. This can lead to frustration and decreased engagement, as users are unsure if their ideas will get a response or funding. 
![Image](https://user-images.githubusercontent.com/110252255/234439941-c831794a-76e2-4432-936c-7c25d6bc1e43.png)

**Solution**
This ticket introduces a simplified UI for the create experience. There are two major changes:

1. **Simplifying from four create types to just two:** Since we expect users to only use the idea/solution as the top level parent post, we will only expose those options and provide better explanation of what to expect when submitting those post types. We will only show one eye catching create button on the screen.

![Image](https://user-images.githubusercontent.com/110252255/234442069-8d53f001-c70d-4a76-baad-afa99a5fce3a.png)

2. **Introducing a separate create post page:** When a user clicks on the create button, we'd like to navigate them to a separate create post page that will make it easier to write the post without the distraction of the homepage and feed.

![Image](https://user-images.githubusercontent.com/110252255/234442115-521ec8d4-798c-4b9d-a4eb-5621c3f1583b.png)

**User Story**
As a user, I want to have an easy way to create a new post type and understand what to expect.

**Acceptance Criteria**
- On the homepage, a user sees a description under Activity ("Browse through the community’s recent feed or contribute by submitting your idea/solution.") as well as new button on the right side of the screen ("Submit Idea / Solution") per the design
- When a user clicks on the Submit Idea / Solution, they see a "Create New Post" page. 
- The "Create New Post" page follows the structure in the attached designs
  - The main header includes a breadcrumb navigation at the top: DevHub / Create new
  - There are two buttons (Idea and Solution). The default button is Idea. A user can toggle from Idea to Solution.
  - Include all the fields from the design
  - User sees a preview below
  - When a user clicks Submit, they are taken to the homepage where they see their post at the top

**Attachments**
See Figma designs: https://www.figma.com/file/Z3JOMFDryJddA6xJaT3QSt/Create-Experience-UI?node-id=0%3A1&t=ATn6HPZXa8145eN9-1

**Comment by ailisp** [comment]
@ori-near Great idea! Do you have a list in mind about "related resources or FAQs to help users learn how to drive engagement in their post"?

**Comment by ori-near** [comment]
Hi @ailisp – I need to brainstorm on this a bit more. I'm moving this issue to the `Backlog` column and will update once it is ready.

**Comment by ori-near** [comment]
@ailisp Can you please review this ticket, size it, and let me know if you have any questions? Could we add a `good first issue` label to this?

**Comment by ben-jamming-reilly** [comment]
@ori-near Could I pick up this ticket?

**Comment by ori-near** [comment]
Hey @ben-jamming-reilly – sure thing! We have assigned this ticket to you and move it to `In Progress`. We kindly request that you submit a pull request with your solution within one week. If you are no longer able to work on this issue, please let us know so we can reopen it for another developer to take on. Once again, thanks so much and we look forward to your contribution.

**Comment by ori-near** [comment]
Hi @ben-jamming-reilly – thanks so much for submitting a preview. Overall it looks great. Just a few minor edits, as we discussed:

- Create post preview section: The preview should show the correct post type name and icon. For the solution post type, please change "Maximum amount:" to "Requested amount:" and "Supervisor:" to "Requested Sponsor")
- Create solution Total Amount field: Please make that field empty. Also, do not allow the user to type characters other than whole numbers and do not allow 0.

**Comment by ori-near** [comment]
Hi @ben-jamming-reilly – just wanted to check in to see if there's anything you need from @ailisp or @frol to move this ticket over the finish line?
