### ISSUE TITLE
Tagging/mentions doesn't work if you do not follow anyone

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#200]
**Describe the bug**
When an account doesn't follow anyone, you cannot use the tagging/mentions feature.

**To Reproduce**
1. A user that doesn't follow anyone should create a new idea/solution or try to reply to any post.
2. Type @t in the description.
3. The user does not see any suggested users.
![Screenshot 2023-07-11 at 5 41 36 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ee3edb29-9791-4c8c-8d88-b282c232e806)

**Expected behavior**
User should see suggested user names:
![Screenshot 2023-07-11 at 5 43 12 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ff863b7a-7301-4a8c-957c-5458b30ff6a0)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 114.0.5735.198 (

**Comment by ori-near** [comment]
@petersalomonsen Could you please look at this when you get a chance? Thanks so much.

**Comment by petersalomonsen** [comment]
@ori-near I am not able to reproduce this. I'm also on mac using chrome. Note that the mentioning popup is only active for the last character in the post. So if you have a space after, or any other character then it will not show up. Could that be the issue?

<img width="588" alt="image" src="https://github.com/near/neardevhub-widgets/assets/9760441/ba2f2dcb-5ebd-4087-959c-14d318cf1071">

**Comment by ori-near** [comment]
Hi @petersalomonsen – I'm still running into this issue no matter what I type in after "@". Happy to do a screen share with you if that helps.

**Comment by petersalomonsen** [comment]
This appears to be because of the common AccountAutocomplete widget (that is also used for regular posts), that require that you follow someone in order to display completions, as you can see from the source here:

https://near.org/near/widget/ComponentDetailsPage?src=near/widget/AccountAutocomplete&tab=source

In your case the account is not following anyone:

![image](https://github.com/near/neardevhub-widgets/assets/9760441/55b435cb-2add-4f18-a776-a73c0bd06b81)

**Comment by ori-near** [comment]
Hi @petersalomonsen – thanks for finding the root cause of this bug. It seems like once I followed someone, I was able to use the tagging feature. This seems to be a problem outside of DevHub on near.org.

**Comment by petersalomonsen** [comment]
This is where the fix needs to be done ( in the AccountAutocomplete component under the `near-discovery-components` repository ):

https://github.com/near/near-discovery-components/blob/develop/src/AccountAutocomplete.jsx#L10

**Comment by Megha-Dev-19** [comment]
@ori-near I would like to take this ticket

**Comment by ori-near** [comment]
@Megha-Dev-19 – thanks so much for fixing this issue, which has existed for months. Appreciate your quick fix.
