### ISSUE TITLE
Clicking on Submit Idea / Solution opens up Solution post that misses the funding field

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#213]
**Describe the bug**
When a user clicks on the "Submit Idea / Solution" create button, the second Solution post type loads by default without the funding fields. Additionally, the preview shows a ":" instead of the expected solution preview. There are two problems with this: One, the default view should show the idea type, since it's first. Second, the missing funding fields may lead a user to not including funding details.

**To Reproduce**
1. Go to neardevhub.org
2. Click on Submit Idea / Solution
3. See solution post without the funding fields and the incorrect preview: 
![Screenshot 2023-07-27 at 2 16 53 PM](https://github.com/near/neardevhub-widgets/assets/110252255/63f334e8-811d-424b-ad70-2f0ed70a0c2c)
4. The user can only see the correct fully loaded solution post by clicking on the Solution button again at the top.

**Expected behavior**
The idea post should load first. And the solution post should load correctly:
![Screenshot 2023-07-27 at 2 18 43 PM](https://github.com/near/neardevhub-widgets/assets/110252255/a4f4e31e-c007-4415-84cf-4f824d2992d5)

**Comment by elliotBraem** [comment]
I can pick this one up @ori-near

**Comment by ailisp** [comment]
@elliotBraem I'll quickly fix this by revert a PR
