### ISSUE TITLE
Pin a post to a community

### ISSUE THREAD

**Issue by codingshot** [near/neardevhub-widgets#219]
**Is your feature request related to a problem? Please describe.**
As a community manager, many posts get lost due to community discussion. Would be awesome if could pin a post as main cta to show up as a top pinned post 
**Describe the solution you'd like**
Allow moderators of a community to pin a post to the top of a community if it has the community tag. Show option to unpin current post if their is already a pinned post. A notification letting people know that account pinned a post in community is a nice to have 

**Describe alternatives you've considered**
Allow multiple posts to be pinned and unpinned 
**Additional context**
For gigs process this may be the main instructions. This may be a gig or idea for exposure

**Comment by ori-near** [comment]
Hey @codingshot – thanks for creating this! We already have another similar ticket for this, so please feel free to add any comments:
https://github.com/near/neardevhub-widgets/issues/159

Going to close this one as duplicate for now. Thanks!
