### ISSUE TITLE
Introduce better markdown functionality for posts

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#221]
**Problem**
Our current markdown functionality on DevHub is not intuitive and causes confusion. We need to make it easier for people to create, format, and edit content.

**User Story**
As a DevHub user, I want to have a simple and user-friendly markdown functionality so that I can easily create and edit content without feeling confused.

**Acceptance Criteria**
- The text editor for posts (and community pages) should display a toolbar with intuitive buttons for common markdown formatting options, including: Heading, bold, italics, quote, code block, links, bulleted lists, numbered lists, task list, @mention, referencing another ticket, etc.
- User should see live previews for their markdown as they type, providing-real time feedback on how the content will render
- User can create line breaks, and the preview/rendering should format them in [separate lines](https://github.com/near/neardevhub-widgets/issues/221#issuecomment-1670440297) instead of side by side.

**Comment by elliotBraem** [comment]
This looks good to me, although there are a couple things to consider: 

These type of editors come from light weight external packages -- implementing it from scratch ourselves would take quite a bit of work.

For example, [this widget](https://near.social/efiz.near/widget/every.markdown.create) is an embedding of [react-markdown-editor-lite](https://github.com/HarryChen0506/react-markdown-editor-lite). After exploring the package more, it doesn't look like plugins are as easily configurable. 

An alternative is [Simple MDE](https://github.com/sparksuite/simplemde-markdown-editor), which I've whipped up a basic implementation of it in a widget [here](https://near.social/efiz.near/widget/SimpleMDE) (1 hour). This one looks more feature reach and I've been able to easily extend it with custom plugins -- this will be helpful for @mention, referencing other tickets, etc.

Is the live preview of markdown remaining as implemented today? (below the post)

If Simple MDE is good to go, then I would size this as S. You can assign to me.

**Comment by ori-near** [comment]
Hey @elliotBraem – to clarify, we already have @mentions functionality that @petersalomonsen developed in https://github.com/near/neardevhub-widgets/issues/119

Feel free to make a call on implementation here and reach out to @ailisp if you have any questions or concerns.

**Comment by elliotBraem** [comment]
You can assign this to me @ori-near and move to in progress, I'll open my draft PR

**Comment by ori-near** [comment]
Awesome, thanks @elliotBraem. BTW one AC I forgot to include that we discussed on our call last week is to fix the current issue when people create line breaks:

![Image](https://github.com/near/neardevhub-widgets/assets/110252255/238e028f-145d-49ff-ac6a-738a803213e4)


Just updated the AC.

**Comment by carina-akaia** [comment]
Related ticket: https://github.com/near/neardevhub-widgets/issues/178

**Comment by elliotBraem** [comment]
Will create a separate PR for #178. 
I'd like to move the community wiki editor and bio field to this story as well. See my comment [here](https://github.com/near/neardevhub-widgets/pull/232#issuecomment-1673894199).

The PR is ready for review: #232

**Comment by ori-near** [comment]
Hey @ailisp – can you please work with @elliotBraem to move this ticket over the finish line? Thanks so much.

**Comment by elliotBraem** [comment]
It was quite the merge conflict! All good now. @ori-near @ailisp
