### ISSUE TITLE
[Projects] Implement project creation form

### ISSUE THREAD

**Issue by carina-akaia** [near/neardevhub-widgets#223]
On the community projects page ( `pages/community/projects.jsx` ), there's a toolbar with "Create project" button. This toolbar should be reimplemented as an accordion collapsed by default, but expanding once "Create project" button is pressed, showing a project creating form with three text fields: "Tag", "Name", and "Description". In addition, the "Cancel" and "Create" buttons should be shown in place of "Create project", and on "Cancel" button click the accordion should collapse back into the toolbar with the singular button. The data from text fields should be collected and passed to the "onClick" callback of the "Create button", which should call `DevHub.create_project({ tag, name, description })` ( the contract side update isn't finished and merged yet, so there's no need to check what happens in the blockchain.

**Comment by Tguntenaar** [comment]
Alright I can pick this up today!
