### ISSUE TITLE
Filtering by label provided in the URL is not respected

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#226]
**Describe the bug**

Using label chips on the posts should apply filtering by that label, but it simply shows an unfiltered list of posts:

https://near.org/devgovgigs.near/widget/gigs-board.pages.Feed?label=near-sdk-js

This link should only show the posts labeled with `near-sdk-js`, but it does not.

**To Reproduce**
1. Go to the feed
2. Click on any label chip on any post to get navigated to `?label=xxx` page
3. The list of posts is unfiltered

**Expected behavior**

The list should be filtered as if you entered the label in the search field. Also, the search field should be populated with the value provided in the URL.

**Screenshots**

<img width="959" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/f0a87e06-d24b-479e-a14a-35b6f5cb7d66">

**Desktop:**
 - OS: any
 - Browser any
 - Version latest

**Smartphone:**
 - Device: any
 - OS: any
 - Browser: any
 - Version any

**Comment by jaswinder6991** [comment]
I can take this. Can you please assign it to me.

**Comment by ori-near** [comment]
Hi @jaswinder6991 thanks so much for expressing interest 🔥. We appreciate your willingness to contribute!

We have assigned this ticket to you and would like to kindly request that you submit a pull request with your solution within one week. We moved this ticket to In Progress to indicate that you are working on it. If you are no longer able to work on this issue, please let us know so we can reopen it for another developer to take on. Once again, thanks so much and we look forward to your contribution.

**Comment by jaswinder6991** [comment]
Thanks @ori-near 
Here is what I found, the label prop does not really work on the feed widget, you instead have to do ```tag``` , so the working URL should be.
https://near.org/devgovgigs.near/widget/gigs-board.pages.Feed?tag=near-sdk-js

As I went down the widget rabbit hole, I found out the tag widget which is this:
https://near.org/devgovgigs.near/widget/gigs-board.components.atom.tag 

Here is the problem in this widget, current code:
```
function href(widgetName, linkProps) {
  linkProps = { ...linkProps };

  if (props.nearDevGovGigsContractAccountId) {
    linkProps.nearDevGovGigsContractAccountId =
      props.nearDevGovGigsContractAccountId;
  }

  if (props.nearDevGovGigsWidgetsAccountId) {
    linkProps.nearDevGovGigsWidgetsAccountId =
      props.nearDevGovGigsWidgetsAccountId;
  }

  if (props.referral) {
    linkProps.referral = props.referral;
  }

  const linkPropsQuery = Object.entries(linkProps)
    .filter(([_key, nullable]) => (nullable ?? null) !== null)
    .map(([key, value]) => `${key}=${value}`)
    .join("&");

  return `/#/${nearDevGovGigsWidgetsAccountId}/widget/gigs-board.pages.${widgetName}${
    linkPropsQuery ? "?" : ""
  }${linkPropsQuery}`;
}

const Tag = ({ label }) => (
  <a href={href("Feed", { label }, label)}>
    <span
      class="badge me-1 text-dark fw-normal"
      style={{ border: "1px solid #D0D5DD" }}
    >
      {label}
    </span>
  </a>
);
```

In the component code,
1. ```<a href={href("Feed", { label }, label)}>``` should be just  ```<a href={href("Feed", { label })}>``` as the href function only takes two arguments.
2. Also, as label prop does not work and instead tag prop works, it should be  ```<a href={href("Feed", { tag })}>```

This is what I could find out quickly. This is one way to solve it.
Another way that I am looking into is, in one of the parents element, we could also just make label=something work, that does not work right now. 

What do you suggest?

**Comment by ori-near** [comment]
Hi @jaswinder6991 thanks so much for looking into this. I'm going to add @frol or @ailisp to chime in here.

**Comment by ailisp** [comment]
@frol @jaswinder6991 Good catch and great investigation! According to @jaswinder6991 's investigation, replacing "label" with "tag" in the url works. Makes label also work is not difficult, the question is whether we want that from product perspective? 


@ori-near we'll let you decide.

**Comment by carina-akaia** [comment]
This issue should already be fixed, please check again

**Comment by ailisp** [comment]
@carina-akaia Just test it isn't. Let me clarify: we used to support `label=foo` in url to filter posts with foo label. So Frol has some URLs of this kind. Later, label is renamed to tag. You can see main page search bar is "Search by tag" now. And only `tag=foo` in url works. This is technically right but some previously working URL would not work. The problem is
should we add label=foo support for backward compatibility?

**Comment by carina-akaia** [comment]
@ailisp now I get it, thanks!

**Comment by ori-near** [comment]
Hi @ailisp and @jaswinder6991 – sorry for my delayed response. I think since we decided to change labels to tags, we should just support tags moving forward. Is there a reason why you think we'd need backward compatibility for labels too?

**Comment by ailisp** [comment]
I think it's fine to drop labels. @frol ^

**Comment by frol** [comment]
Yes, I am fine with dropping `label`, no need for backward compatibility. This issue is now resolved as clicking on tags of the posts works as expected now.
