### ISSUE TITLE
Ability for Communities to Add Widgets in Their Page

### ISSUE THREAD

**Issue by nearbuild** [near/neardevhub-widgets#228]
**Is your feature request related to a problem? Please describe.**
As a Dev Community on BOS I want to provide a custom experience on BOS, i.e. add tabs that display custom components, for ex, DAO feed, social feed, job board from NEAR Horizon.

**Describe the solution you'd like**
In settings to add Widget tabs where community admins put tab name, add widget path.

**Describe alternatives you've considered**
Forking devhub pages and putting into a bigger components. However, this wont be as clean and wont lead to DevHub being source of truth for discovery.

**Comment by jaswinder6991** [comment]
The new community addon framework lets you add custom widgets as tabs on the community page. 
The addons(custom widgets) however are limited to only below for now:
- The new blog plugin
- Telegram (Integration)
- Github (Integration)
- Kanban
- Wiki
