### ISSUE TITLE
Make current DevHub landing page mobile friendly

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#231]
**Problem**
Currently, any users who access DevHub on their mobile devices face challenges in reading content due to a lack of mobile-friendly responsive design. This makes it painful to navigate quickly and find relevant information on the go.

**User Story**
As a mobile user, I want a mobile friendly experience on DevHub similar to neardevgov.org, so that I can easily find and read DevHub content on the go without any hindrances.

**Acceptance Criteria**
- DevHub layout is optimized for mobile using best practices (e.g. card based layout, sticky navigation bar, etc)
- User can easily browse and search for content on DevHub from posts to communities

**Comment by Tguntenaar** [comment]
@ori-near Could you please provide additional requirements for both acceptence criteria? Might be usefull to use the MoSCoW method.

**Comment by ori-near** [comment]
Hey @Tguntenaar – as we discussed on the call today, we will simplify this ticket for just minor improvements to the existing DevHub platform. Can you please update this ticket to reflect the scope that you've completed?

@jaswinder6991 – can you please create a separate ticket for mobile support as part of the https://github.com/near/neardevhub-widgets/milestone/9?

**Comment by ori-near** [comment]
We will revisit mobile as part of the redesign epic.
