### ISSUE TITLE
[Communities] Homepage sidebar shows Telegram icon even when no handle is set in the create/edit page

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#236]
**Describe the bug**
When I created the new [Developer DAO](https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=developer-dao) community, I did not enter a Telegram handle in the Telegram handles on the Community Create page. However, the homepage sidebar still shows a Telegram link.

**To Reproduce**
1. Create a new community and leave the Telegram handles on the About section empty. Click save.
2. Check out the homage sidebar about section and see a Telegram icon that links to https://t.me/.

**Expected behavior**
If a user leaves the Telegram handle field blank, no Telegram icon should show up on the sidebar. 

**Screenshots**
![Screenshot 2023-08-10 at 12 14 08 PM](https://github.com/near/neardevhub-widgets/assets/110252255/fc228f53-46f6-447c-b236-dd79b3a7b506)

![Screenshot 2023-08-10 at 12 08 48 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ccb7c828-7d91-44d9-954a-b530172628da)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest

**Comment by amartyaroy** [comment]
@ori-near 
can you please assign this issue to me i will fix it

**Comment by ori-near** [comment]
Hi @amartyaroy thanks so much for expressing interest 🔥. We appreciate your willingness to contribute!

We have assigned this ticket to you and would like to kindly request that you submit a pull request with your solution within one week. We moved this ticket to In Progress to indicate that you are working on it. If you are no longer able to work on this issue, please let us know so we can reopen it for another developer to take on. Once again, thanks so much and we look forward to your contribution.

**Comment by ori-near** [comment]
This bug is no longer relevant with the introduction of the simplified community flow:
https://github.com/near/neardevhub-widgets/pull/218.
