### ISSUE TITLE
[Communities] Entering multiple telegram handles in community create/edit leads to rendering issues

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#237]
**Describe the bug**
When I created the new [Developer DAO](https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=developer-dao) community, I tried to enter 3 Telegram handles on the Community Create page. However, the homepage sidebar concatenates them into one link with the wrong URL. 

**To Reproduce**

**Problem #1: Sidebar**

1. Create a new community and enter three Telegram links into the Telegram Handles field: `NEARDevHub, neardev, NEAR_Education`. Click Save.
2. Check out the homage sidebar about section and see one concatenated Telegram link
`NEARDevHubneardevNEAR_Education` that points to a concatenated URL `https://t.me/NEARDevHub,neardev,NEAR_Education`

![Screenshot 2023-08-10 at 12 29 44 PM](https://github.com/near/neardevhub-widgets/assets/110252255/f3bc154a-89ce-41ca-a235-cfcc039ce888)

**Problem #2: Telegram page**

1. Create a new community and enter three Telegram links into the Telegram Handles field: `NEARDevHub, neardev, NEAR_Education,`. **Make sure to add a comma** at the end and click Save.
2. Telegram tab shows feeds from the three telegram channels. But then a fourth empty section with a `{"error":"Not Found"}` error message.

![Screenshot 2023-08-10 at 12 30 28 PM](https://github.com/near/neardevhub-widgets/assets/110252255/616c0cc1-6a61-4b77-be24-bc6535d460d2)

**Expected behavior**

- **Problem 1: Sidebar** – User should see a separate Telegram name and link to each one that was entered
- **Problem 2: Telegram Page** – User should not be allowed to enter a comma, and the error message should not load.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Version: Latest

**Comment by bearmans** [comment]
Seems like this was fixed- couldn't replicate, looks to be behaving correctly now

**Comment by ori-near** [comment]
Confirming this was resolved with the recent community sidebar fixes
