### ISSUE TITLE
[Communities] Enhance community admin management and team visibility

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#241]
## Problem
Currently, on the community create/edit page, the experience of setting admins for a community lacks clarity and usability. Users are queried to add admins using comma separators without indication of successful username recognition. The default assignment of admin privileges is unclear. And, there is a noticeable lag in the process. Additionally, the teams tab presents two lists, "Admins" and "Community Moderators" but the distinction between these roles is unclear, leading to potential confusion.

## User Story
As a user managing a community on DevHub, I want a clear method for setting the admins for my community, along with a clear display of those admins on the Teams page.

## Acceptance Criteria

On the community create/edit page: 
- [ ] Change the "Access control" section header to "Community Admins"
- [ ] Improve the UI experience for entering additional admins (see Admin UI Experience options below)

On the Teams tab
- [ ] Change "Admins" title to "Community Admins"

On the community homepage sidebar section:
- [ ] Change "Admins" title to "Community Admins"

## Admin UI Experience

**Option 1**
Require the selection of the primary admin #1 and then offer the ability to add more admins. Display the chosen user's profile picture to confirm successful selection.

![Screenshot 2023-08-11 at 11 56 33 AM](https://github.com/near/neardevhub-widgets/assets/110252255/98038339-d0f8-47b5-947d-03252a3daa7d)

**Option 2:** 
Make the admin #1 required and then add the option to add/delete additional admins within the same field. 

![Screenshot 2023-08-11 at 12 03 22 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ebeb038c-4425-4e5d-a347-3fbb5856c39a)

**Comment by elliotBraem** [comment]
I can pick this one up

**Comment by ori-near** [comment]
Hi @elliotBraem – just checking on this ticket. Can you please clarify what is needed to move this over the finish line? Thanks so much.

CC: @ailisp

**Comment by elliotBraem** [comment]
Dropping this story back to Backlog.
There is progress on this branch if anyone wants to pick that up: https://github.com/near/neardevhub-widgets/pull/246

**Comment by Megha-Dev-19** [comment]
hey @ori-near @elliotBraem, I can pick this one
do we have a confirmation on UI (option 1 or 2)?

**Comment by ori-near** [comment]
Hi @Megha-Dev-19 – I personally prefer option 2. Thank you!

**Comment by Megha-Dev-19** [comment]
@ori-near I don't understand few points
- Remove the "Community Moderators" section: where is it, I couldn't find it
- Replace the existing Group Moderators section with the Community Admins instead of DevHub moderators. So the section should show "Community Admins" title plus the list of community admins (profile picture, name, username).
what does this mean?
