### ISSUE TITLE
Author-based searched is outdated

### ISSUE THREAD

**Issue by nearmax** [near/neardevhub-widgets#248]
**Describe the bug**
When I search for posts from `nearmax.near` I only see very old posts:
![image](https://github.com/near/neardevhub-widgets/assets/35039879/1f766a9e-55b1-4fdb-8656-0bb58bfb54fe)
and it does not show more recent posts that I made:
https://near.social/devgovgigs.near/widget/gigs-board.pages.Post?id=1034

**To Reproduce**
1. Go to https://neardevhub.org/
2. Search for posts made by `nearmax.near`;
3. Observe that https://near.social/devgovgigs.near/widget/gigs-board.pages.Post?id=1034 is not coming up

**Expected behavior**
All posts from `nearmax.near` are shown.

**Comment by ailisp** [comment]
@Rishabhraghwendra18 Thanks for looking into this. This is fixed in #298
