### ISSUE TITLE
Incorrect post link redirect behavior due to hardcoded URL

### ISSUE THREAD

**Issue by Tguntenaar** [near/neardevhub-widgets#254]
**Describe the bug**
The post link of a post is hardcoded which produces incorrect redirecting behaviour when users attempt to access the linked post.

**To Reproduce**
1. Go to a profile page for example [this one](https://near.social/mob.near/widget/ProfilePage?accountId=thomasguntenaar.near)
2. Click on `Posted on Devhub`
3. It will redirect to [the wrong post](https://near.social/devgovgigs.near/widget/Post?id=7)

**Expected behavior**
It should redirect to the right post on the right dynamic domain instead of statically redirecting to `near.social`

**Desktop:**
 - OS: Mac
 - Browser Chrome
 - Version 116.0.5845.140

**Additional context**
The problem is part of neardevhub-contract re-posting implementation: [https://github.com/near/neardevhub-contract/blob/main/src/repost.rs#L7](https://github.com/near/neardevhub-contract/blob/main/src/repost.rs#L7)
It should be a relative link instead of hardcoding the domain name. (remove the https://near.social, keep the `/#/`) 
More generic solution with customization is not needed as we will hopefully will move away from cross-posting.

**Comment by Rishabhraghwendra18** [comment]
Hi @carina-akaia, may I take this issue?

**Comment by carina-akaia** [comment]
> Hi @carina-akaia, may I take this issue?

Are you going to tackle it during this week? If that's the case, yes!

**Comment by Rishabhraghwendra18** [comment]
@carina-akaia may you guide me on how to set up the neardevhub repo on my local. It doesn't have proper documentation.

**Comment by carina-akaia** [comment]
> @carina-akaia may you guide me on how to set up the neardevhub repo on my local. It doesn't have proper documentation.

Hi, all you need is to install Rust 1.69.0 or newer, if you don't have it in your system yet. The most popular way is to use the [official guide](https://www.rust-lang.org/learn/get-started) featuring `rustup` setup utility

**Comment by Rishabhraghwendra18** [comment]
@carina-akaia I am getting this error when running tests, `cargo test`:
```
 error while sending payload: [error sending request for url (http://localhost:18243/): error trying to connect: tcp connect error: Connection refused (os error 111)]
```

**Comment by carina-akaia** [comment]
> @carina-akaia I am getting this error when running tests, `cargo test`:
> 
> ```
> 
>  error while sending payload: [error sending request for url (http://localhost:18243/): error trying to connect: tcp connect error: Connection refused (os error 111)]
> 
> ```
> 
> This looks like happen when `tests/migration.rs` runs

As far as I know, at this moment tests are supposed to be executed in GitHub pipelines as they require a specific setup that involves booting up a localnet. Just create a _draft_ PR and see the test results if you have implemented something already and wanna test it.

**Comment by Rishabhraghwendra18** [comment]
@carina-akaia I have created this draft PR. Looks like it needs approval to run the unit tests because of some branch protection rules.

**Comment by carina-akaia** [comment]
@Rishabhraghwendra18 let's convert it into a normal PR by pressing "ready for review", I suppose this might trigger the pipeline

Also, I left a couple tiny suggestions in the PR comments
