### ISSUE TITLE
Merge essential content from neardevgov.org into neardevhub.org

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#258]
**Problem:**
Currently, we have two websites: https://neardevgov.org (our old identity) and https://neardevhub.org. This is causing confusion for users, as they are not sure which website is most up-to-date. We need to migrate all of the content from the old website.

**User Story:**
As a user on DevHub, I want to find the relevant information in one place so that I do not have to keep track of multiple sources.

**Acceptance Criteria**

Blog Posts
- [ ] All blog posts are moved to DevHub
- [ ] Blog posts must be organized within the appropriate communities
- [ ] Replace mentions of DevGov and DevGigs with DevHub

Social Links
- [ ] Add social links on DevHub (Twitter, Telegram, YouTube)

Newsletter
- [ ] Add NEWSWEEK newsletter signup

Other
- [ ] Redirect https://www.neardevgov.org/ to http://neardevhub.org/
- [ ] Cancel previous hosting plan

**Comment by jaswinder6991** [comment]
Hi @ori-near, could you please assign this to me. Thanks.
