### ISSUE TITLE
Add USDC currency support for solution and sponsorship posts

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#263]
**Problem**
Currently, users are only allowed to select USDT or NEAR for solution and sponsorship posts. However, some users may want to request USDC.

**Solution**
As a user, I want to have the option to request USDC.

**Acceptance Criteria**
- New solution and sponsorship posts display the following currencies: USDC, USDT, NEAR
- Old posts can still retroactively display the currency that was entered when they were created
- There is no error messages when creating solution or sponsorship using either USDC, USDT, or NEAR

**Comment by frol** [comment]
Just for context, USDC contract address is `17208628f84f5d6ad33f0da3bbbeb27ffcb398eac501a31bd6ad2011e36133a1`

https://twitter.com/circle/status/1702306452403278146

**Comment by carina-akaia** [comment]
Hi @frol, what's your estimate for this task?

@ori-near I'd like to take this ticket for the ongoing dev cycle as well, if you don't mind

**Comment by frol** [comment]
@carina-akaia I tried to set it, but GitHub fails to save it right now. I believe it is XS (<1/2 day) of work for implementing and testing it.

**Comment by carina-akaia** [comment]
@frol I'd set S and see how it goes, but I didn't look into it yet. Is it just as simple as adding a enum member?

**Comment by espensimensen** [comment]
@ori-near As we discussed, I can look into this ticket

**Comment by ori-near** [comment]
Hi @espensimensen – this ticket is sized as one day. Do we need to update this? It's quite urgent, as many contributors are seeking this currency but do not have the ability to do so. Can you please provide a date estimate?

**Comment by espensimensen** [comment]
Hi, I'm testing it in my environment right now. I should be able to have a PR ready today

**Comment by ori-near** [comment]
Hi @espensimensen – just wanted to follow up on this ticket. What do you need to move it to done?
