### ISSUE TITLE
Migrate existing GitHub plugin to new framework

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#265]
**Problem**
Currently, community admins are unable to choose if they want to enable or disable the GitHub plugin. They also are unable to customize it within the community settings page.

**User Story**
As a community admin, I want the ability to decide if to enable or disable the GitHub plugin. I also want to clearly understand where to configure this page in a consistent way.

**Acceptance Criteria**
- GitHub plugin aligns with the new framework (#253). So an admin can enable, configure, or remove the plugin in the community settings page.
- If a community admin enables the GitHub plugin, the GitHub tab shows up on the community page navigation. 
- Admin can configure the plugin within the community settings page, not from the old GitHub tab. Remove any instances from the GitHub tab to configure the page from the tab. 
- If a community admin enables the GitHub plugin, they can click configure to customize the the tab name as well as the existing GitHub specific fields, including:
  - Title*
  - GitHub Repository URL*. Note: We will need to add a prefix here (similar to the about links section) that says: "https://github.com/" to make it clear what part of the GitHub URL the user needs to enter. 
  - Ticket type* (Issue, Pull Request)
  - Ticket State*
  - Description*
  - New Column* (plus the supporting fields)
- Community admin should have a way to preview GitHub board from the configure settings. 
- If an admin enables the GitHub plugin, the GitHub field(s) with * above are required
- There is no disruption to old/existing GitHub plugins
- There is migration option provided for existing communities to transition to the new framework

**Comment by elliotBraem** [comment]
Included in this scope should be creating a "CommunityAddon"; an instance in the devhub contract:

```rust
pub struct CommunityAddOn {
    id: String,
    title: String,
    description: String,
    src: String,
    schema: String,
    custom_configurator: String
    icon: String
}
```

Github has it's own custom_configurator.

I think I need more clarity on:

> Admin can configure the plugin within the community settings page, not from the old GitHub tab. Remove any instances 
> from the GitHub tab to configure the page from the tab.

In #253, we had criteria: "A community component needs to support two view modes: one for the component to appear in the new tab, and one for configuration section"

This sounds like configuration should be limited to "Configure Community" instead, rather than option to modify in tab, too? No issue in either, but should be clear for scope.


> Community admin should have a way to preview GitHub board from the configure settings.

Is this currently supported @carina-akaia ? I couldn't find a community I'm admin of that I could explore this for.

**Comment by ori-near** [comment]
Hi @elliotBraem – I think the scope you referenced in #253 was from @petersalomonsen's original technical docs, below the user story. 

**Current State:** The only way to configure a GitHub board is through the tab itself:
![Screenshot 2023-09-22 at 4 07 49 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ddcbbc60-e90a-4931-9f2a-1940ffd7cf2f)
![Screenshot 2023-09-22 at 4 08 25 PM](https://github.com/near/neardevhub-widgets/assets/110252255/1d09a718-123d-4027-8000-e68a57845cb2)

**Desired State:** We want to remove all these config references from the tab. And make them available through the Community Configuration section only.

Please let me know if this clarifies.
