### ISSUE TITLE
Migrate existing Kanban board plugin to new framework

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#266]
**Problem**
Currently, community admins are unable to choose if they want to enable or disable the Kanban Board plugin. They also are unable to customize it within the community settings page.

**User Story**
As a community admin, I want the ability to decide if to enable or disable the Kanban plugin. I also want to clearly understand where to configure this page in a consistent way.

**Acceptance Criteria**
- Kanban Board plugin aligns with the new framework (#253). So an admin can enable, configure, or remove the plugin in the community settings page.
- If a community admin enables the Kanban Board plugin, the Kanban Board tab shows up on the community page navigation. 
- Admin can configure the plugin within the community settings page, not from the old Board tab. Remove any instances from the Board tab to configure the page from the tab. 
- If a community admin enables the Kanban Board plugin, they can click configure to customize the the tab name as well as the existing Kanban Board specific fields, including:
  - Board Title*
  - Board Description*
  - Tags to include
  - Tags to exclude
  - New Column* (plus the supporting fields)
- Community admin should have a way to preview Kanban Board from the configure settings. 
- If an admin enables the  Kanban Board plugin, the  Kanban Board field(s) with * above are required
- There is no disruption to old/existing Kanban Board plugins
- There is migration option provided for existing communities to transition to the new framework

**Comment by elliotBraem** [comment]
Included in this scope should be creating a "CommunityAddon"; an instance in the devhub contract:

pub struct CommunityAddOn {
    id: String,
    title: String,
    description: String,
    src: String,
    schema: String,
    custom_configurator: String
    icon: String
}

Kanban has it's own custom_configurator. After this is added, most of the scope should be completed because of the framework. This migration looks minimally invasive.

Like Github boards, 
> Community admin should have a way to preview Kanban Board from the configure settings.

Is this currently supported @carina-akaia ? I couldn't find a community I'm admin of that I could explore this for.

Although it depends on answers above, I am leaning towards M effort. @ori-near

**Comment by carina-akaia** [comment]
@elliotBraem yes, the previews are implemented from the very beginning. But please don't make any decisions on this until #250 is released, because I've already established the better architectural solution for the given task. Same for #265
