### ISSUE TITLE
Migrate existing Wiki plugin to new framework

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#267]
**Problem**
Currently, community admins only have the option to enable up to two Wiki plugins in the community settings page. However, some communities may want to add additional wikis.

**User Story**
As a community admin, I want the ability to decide if to enable or disable multiple Wiki pages, using a consistent way as other plugins.

**Acceptance Criteria**
- Wiki plugin aligns with the new framework (#253). So an admin can enable, configure, or remove the plugin in the community settings page.
- If a community admin enables the Wiki plugin, the Wiki tab shows up on the community page navigation. And the page itself is populated with the Wiki content set in the Wiki plugin
- If an admin enables the Wiki plugin, they can click configure to customize the the tab name as well as the Wiki specific fields, including:
  - Content (must support markdown language, enabled by https://github.com/near/neardevhub-widgets/issues/178)
- Community admin should have a way to preview Wiki from the configure settings. 
- If an admin enables the Wiki plugin, the Wiki content field is required
- There is no disruption to old/existing Wiki plugins
- There is migration option provided for existing communities to transition to the new framework

**Comment by elliotBraem** [comment]
Included in this scope should be creating a "CommunityAddon"; an instance in the devhub contract:

```rust
pub struct CommunityAddOn {
    id: String,
    title: String,
    description: String,
    viewer: String,
    configurator: String,
    icon: String
}
```

Wiki has it's own schemas, but will need a configurator widget created. After this is added, most of the scope should be completed because of the framework. This migration looks minimally invasive.
