### ISSUE TITLE
Introduce new Blog plugin

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#268]
**Problem**
Communities lack a dedicated plugin for displaying content such as community blog posts or announcements.

**User Story**
As an admin, I need a dedicated blog plugin to display labeled content in a feed-like manner for my community.

**Acceptance Criteria**
- Introduce a new Blog plugin that aligns with the new framework (#253). So an admin can enable, configure, or remove the plugin in the community settings page.
- If a community admin enables the Blog plugin, the Blog tab shows up on the community page navigation. And the page itself is populated with the Blog content set in the Blog plugin.
- If an admin enables the Blog plugin, they can click configure to customize the the tab name as well as the Blog specific fields, including:
  - Desired tags (comma-separated) for inclusion and exclusion.
  - Display type: Feed or grid
- Community admin should have a way to preview Blog from the configure settings. 
- If an admin enables the Blog plugin, the Blog content field is required

**Comment by jaswinder6991** [comment]
The current story addresses the need for a dedicated blog plugin to display blogs for community pages. I have created a story for a feature for the **creation** of blogs that the plugin would eventually display. Here is the story: https://github.com/near/neardevhub-widgets/issues/269

**Comment by jaswinder6991** [comment]
We have decided to not do #269 for now as it introduces some complexity which might not be important for the mvp. Nonetheless I want to highlight that along with this current ticket which specifies display of a blog feed and its configuration on the community page on the basis of a blog tag (or something relevent), we also need to take care of the blog creation process, meaning how admins can create blogs. 
One way to do this is to create simple posts on the activity feed with the blog tag and then render the blog feed with the blog tag using the blog plugin from this ticket. 
Second way is to give a create blog button on the plugin itself which uses the underlying post_type only but the creator form is different than it is right now for usual posts. 
@elliotBraem @Tguntenaar can you share your views if the second way is a big overhead and takes more than a day?
