### ISSUE TITLE
Create community blogs on Devhub

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#269]
**Problem**
Devhub currently lacks a blog creation feature, limiting communities from publishing their blogs effectively.

**User Story**
As a community admin, I want the ability to create blogs that are closely associated with my community to enhance communication and engagement.

**Acceptance Criteria**
1. Introduce a dedicated "Create Blog" component accessible to community admins. The "Create Blog" component should include the following essential features:
**Header Image**: Allow community admins to upload a header image for the blog. Provide a default image option for simplicity for now. 
**Title**: Provide a field to enter the title of the blog.
**Author**: Include an author field where the admin can specify the author of the blog.
**Date Posted**: Automatically capture and display the date when the blog is created or posted.
**Community** Association: Ensure that each blog is associated with a specific community, allowing admins to link the blog to their community.
**Editing and Deletion**: Admins should have the capability to edit or delete the blogs they create.

2. Integration with Community Blog Plugin:
Ensure that the blogs created using this feature are seamlessly integrated with the Blog plugin introduced [here](https://github.com/near/neardevhub-widgets/issues/268)

3. The blogs created should not be displayed as regular posts on the activity feed. This can be handled at the activity feed level using filters too.

4. Preview cards for the Blogs should be different than usual devhub posts.

**Comment by jaswinder6991** [comment]
The Blog plugin introduced in the Community addon framework addressed this. Except the **Author** feature. I am actually confused if we need Author field because it begs the question if we would allow other community members to publish blogs for a community or just the admins. 
@ori-near @elliotBraem what do you think?

**Comment by ori-near** [comment]
Hi @jaswinder6991 – let's leave it as an admin only feature for now. And we can revisit if we get feedback/requests.
