### ISSUE TITLE
Create Hero section for the new Devhub homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#270]
## Problem

The current Devhub homepage does not have an updated Hero section that aligns with our new brand design, which affects the overall user experience for developers and fails to effectively communicate Devhub's vision and offerings.

## User Stories

- As a developer visiting the Devhub homepage, I want to understand Devhub's vision and its core offerings immediately from the Hero section.
- As a developer, I expect the Hero section to have a compelling design and copy that aligns with the new brand design of Devhub.

## Acceptance Criteria

- [ ] The Hero section should have an updated visual design in line with the new brand design.
- [ ] The copy of the Hero section should be compelling and effectively communicate the Devhub vision and its core offerings. (Attached below)

## Assets

Copy - As mentioned in the Figma
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1086&mode=design&t=QfZzsUC8hiE6i5Sl-4)

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325

**Comment by jaswinder6991** [comment]
Closing as this has been merged to Develop branch already.

**Comment by jaswinder6991** [comment]
Resolved by #335
