### ISSUE TITLE
Create Get Support section for the new homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#271]
## Problem

Developers who come to Devhub currently do not find a clear outline of what support they can get and how they can get it. This makes it difficult for them to get help or to look for resources they need. 

## User Stories

- As a developer visiting Devhub's homepage, I want to see what support can I get.
- As a developer visting Devhub's homepage, I want more details(or links to more resources) on Individuals supports that Devhub provides. 

## Acceptance Criteria

- [ ] Upon landing on Devhub's homepage, a developer should easily identify a section or feature dedicated to the support options available.
- [ ] This support section should be prominently displayed or easily accessible to ensure developers don't overlook it.
- [ ] For each support option listed, there should be a brief description that provides a clear understanding of what that support entails.
- [ ] Each support option should be accompanied by relevant links or buttons directing developers to detailed resources or pages related to that specific support.
- [ ] The section should strictly follow the provided Figma design(linked below) and adhere to the exact copy specifications. This ensures a consistent and cohesive user experience aligned with Devhub's brand and design standards.

## Assets

Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1192&mode=design&t=QfZzsUC8hiE6i5Sl-4)

Copy - As mentioned in the Figma design.

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325

**Comment by jaswinder6991** [comment]
Resolved by #335, merged to main.
