### ISSUE TITLE
Create a Communities section for the new homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#272]
## Problem

The homepage lacks a section for the developers to understand and engage with the various communities within the NEAR developer ecosystem.

## User Stories

- As a developer interested in the NEAR ecosystem, I want to discover different communities available to understand their contributions and significance.
- As a developer, I want guidance on how to effectively engage with these communities based on their focus.

## Acceptance Criteria 

- [ ] The Communities section should provide clear insights into what are communities on Devhub and how they work.
- [ ] The section should have featured communities list and their respective links for developers to browse these communities in detail.

## Assets

- Copy - Mentioned in the Designs
- Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1207&mode=design&t=QfZzsUC8hiE6i5Sl-4)

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325

**Comment by jaswinder6991** [comment]
Resolved by #335 (merged to main)
