### ISSUE TITLE
Create a newsletter and social links section for the new homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#273]
## Problem

Currently on the Devhub homepage, we do not provide a section where users can sign up to our Newsletter and find our other social media links. This makes it hard for the users to stay updated with Devhub's latests announcements and other social media links. 

## User Stories

- As a user visiting Devhub, I want to signup for receiving a newsletter. I want to input my email and get a confirmation that my email was submitted successfully. 
- As a user visiting Devhub, I want to see different social media links for Devhub. Currently Telegram, Twitter and Youtube. 

## Acceptance Criteria

- [ ] User should be signed up for the newsletter successfully. 
- [ ] User should be displayed a success message if sign up was complete.
- [ ] User should be displayed an error message if any.
- [ ] The email signup input field should have basic email checking regex to avoid accepting incorrect email addresses.
- [ ] User should see the following social media links: Telegram, Twitter and Youtube

## Assets

Copy - As mentioned in the Figma

Figma - [Link
](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=530-161&mode=design&t=kz7jPtBbx7bc3yAO-4)

**Comment by jaswinder6991** [comment]
We will be using Mailchimp for Newsletter. We are still setting it up, once that is done, I will update the ticket with necessary API details for the newsletter sign up to work.

**Comment by itexpert120** [comment]
Assign this ticket to me

**Comment by jaswinder6991** [comment]
Resolved by #377
