### ISSUE TITLE
[Communities] Give DevHub moderators the ability to set Featured Communities on homepage (FRONT END)

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#275]
**Problem**
As part of https://github.com/near/neardevhub-contract/issues/36, we made it possible to set the featured communities on the homepage on the contract side. However, admins do not have the ability to set the featured communities through the UI. Currently, they have to rely on developers to modify the smart contract.

**User Story**
As a DevHub admin, I need an easy way to update the features communities on the homepage so that I can showcase various communities without relying on developers to change the code.

**Acceptance Criteria**
- An "Admin" link is visible in the header navigation, visible and accessible only to DevHub admins (not community admins!)
- When a DevHub admin clicks the Admin button, they see a settings page with section for configuring the featured communities
- Within the settings section, DevHub admins can **edit** communities to display on the homepage. The interface for this can be super simple ... just need to solve the goal.
- The UI show a maximum of 5 featured communities, to support the current display limit
- Once the admin clicks save, the changes are instantly reflected on the homepage
- The admin UI should prevent the user from accidentally showing fewer than 4 communities.

Note: It would be great if we can incorporate the label/team permissions functionality (https://github.com/near/neardevhub-widgets/issues/129) into this new admin/settings page. So that there's just one admin page with all the relevant settings.

**Comment by carina-akaia** [comment]
Hi @ori-near, would a community handle input field be enough for adding communities to the list of featured?

**Comment by ori-near** [comment]
Hi @carina-akaia – yes, that's fine.

**Comment by ori-near** [comment]
@carina-akaia Here we go:
https://github.com/near/neardevhub-widgets/issues/315

**Comment by carina-akaia** [comment]
> @carina-akaia Here we go:
> 
> https://github.com/near/neardevhub-widgets/issues/315

Would you like me to take it later?

**Comment by carina-akaia** [comment]
## Implementation demo

- [Mainnet](https://near.org/carina.akaia.near/widget/gigs-board.pages.Feed?nearDevGovGigsContractAccountId=devgovgigs.near)

**Comment by carina-akaia** [comment]
@ori-near please perform QA using the demo ( notice that it's connected to the production contract! ) and give me your feedback

**Comment by ori-near** [comment]
Hi @carina-akaia – I took a look at the main net link you sent but don't see the admin page in the navigation menu. Can you please check? Thank you.
![Screenshot 2023-10-19 at 3 45 04 PM](https://github.com/near/neardevhub-widgets/assets/110252255/3c6016c0-9252-4be7-9a71-ea79e4320fe7)

**Comment by jaswinder6991** [comment]
We have to migrate this solution to the new Devhub app, @ori-near should I create a new ticket or we edit this ticket to do it?

**Comment by carina-akaia** [comment]
@jaswinder6991 it's already migrated in the PR

**Comment by ori-near** [comment]
Hi @jaswinder6991 – can you clarify what you mean here? This solution is independent of before or after Alpha. The solution needs to exist regardless. @carina-akaia what's the status of this ticket?

**Comment by ori-near** [comment]
Hi @carina-akaia – updated the scope of this ticket to 5 communities, which reflects the new design.

**Comment by ori-near** [comment]
> We have to migrate this solution to the new Devhub app, @ori-near should I create a new ticket or we edit this ticket to do it?

Hey @jaswinder6991 – please create a new precursor ticket with the following scope: 1) Turn the hard-coded communities on the new alpha page with the actual blockchain data. Then update this existing ticket to focus on the admin part.

**Comment by Tguntenaar** [comment]
I can pick up this ticket to finish it including the extra scope @ori-near mentioned.

**Comment by Tguntenaar** [comment]
@ori-near this ticket is ready for review


[Preview](https://near.org/geforcy.near/widget/app?page=admin)


Acceptance Criteria:

- [x] An "Admin" link is visible in the header navigation, visible and accessible only to DevHub admins (not community admins!)
- [x] When a DevHub admin clicks the Admin button, they see a settings page with section for configuring the featured communities
- [x] Within the settings section, DevHub admins can edit communities to display on the homepage. The interface for this can be super simple ... just need to solve the goal.
- [x] The UI show a maximum of 5 featured communities, to support the current display limit
Once the admin clicks save, the changes are instantly reflected on the homepage
- [x] The admin UI should prevent the user from accidentally showing fewer than 4 communities.



[PR 500! 🎉](https://github.com/near/neardevhub-widgets/pull/500)

**Comment by Tguntenaar** [comment]
Feedback from Ori on this ticket is found [here](https://github.com/near/neardevhub-widgets/issues/315#issuecomment-1821939223).

Since both ticket #315 and #275 are so related I will continue to address the feedback on that branch and close this ticket.
