### ISSUE TITLE
Update Activity Feed Page aligned with the new homepage design

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#278]
## Problem
The new homepage design would leave the [current](https://near.social/devgovgigs.near/widget/gigs-board.pages.Feed) activity feed misaligned with the new design. This makes the experience for the developers less cohesive and uniform across Devhub.

## Describe the solution you'd like
We propose the changes to the activity feed page using the new designs. Refer to the Figma design below. 

## Acceptance Criteria
- [ ] Activity Feed page should have the new header layout
- [ ] Activity feed should have the new banner section
- [ ] Activity feed page should follow the Figma design attached

## Assets
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=328-2&mode=design&t=6RHKfTz0HRC3hqtD-4)

**Comment by itexpert120** [comment]
Assign this to me

**Comment by jaswinder6991** [comment]
Resolved by #351
