### ISSUE TITLE
Update the All Communities Page with the new design

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#279]
## Problem
The current "All Communities" [page](https://near.social/devgovgigs.near/widget/gigs-board.pages.communities) does not align with the updated homepage design, creating an inconsistent experience for users navigating Devhub.

## Describe the solution you'd like
We propose redesigning the "All Communities" page using the same brand guidelines and design elements from the recently updated homepage. Specifically, the changes will focus on the header and banner design to ensure visual consistency across Devhub. Refer to the Figma design below.

## Acceptance Criteria

- [ ] "All Communities" page should feature the new header layout consistent with the homepage design.
- [ ] The page should include the new banner section, mirroring the updated design elements of the homepage.
- [ ] The "All Communities" page should strictly adhere to the Figma design provided.

## Assets

Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=289-1351&mode=design&t=kz7jPtBbx7bc3yAO-4)

**Comment by itexpert120** [comment]
Can you assing this to me as well?

**Comment by jaswinder6991** [comment]
Resolved by #342
