### ISSUE TITLE
Create a Contribution Path Section on the New Homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#280]
## Problem
Developers currently lack a clear and structured path to engage and contribute to Devhub, making it challenging for newcomers to participate effectively.

## User Stories
- As a developer, I want to see clear ways of contributing to the ecosystem and respective details of each option.
- As a developer, I want to know what all different areas I can contribute to at NEAR and at Devhub.

## Acceptance Criteria
- [ ] The Devhub page should display a structured contribution pathway that offers clarity on different ways a developer can engage with the ecosystem.
- [ ] Each contribution method should be accompanied by a brief description or set of instructions, ensuring that developers understand the requirements and steps involved.
- [ ] Navigation to the contribution pathway should be intuitive, ensuring new visitors can easily locate this section.

## Assets
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1272&mode=design&t=QfZzsUC8hiE6i5Sl-4)
Copy - As outlined in Figma

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325
