### ISSUE TITLE
Store solution post parameters as separate fields apart from description

### ISSUE THREAD

**Issue by carina-akaia** [near/neardevhub-widgets#285]
# Problem

Currently, the solution post type adds only `name` and `description` fields to the post snapshot structure.

This creates issues, when it is impossible to edit and atomically show certain parameters of the solution post, like requested amount of funds, currency, or requested sponsor.

# User story

As a DevHub developer, I need to be able to get and store solution post metadata separately from the description, so that I can implement features that rely on solution post metadata fields.

# Acceptance criteria

1. The solution post data structure ( `Submission` ) has the following properties:

- `amount: Option<Balance>`
- `sponsorship_token: Option<SponsorshipToken>`
- `requested_sponsor: Option<AccountId>`

2. Regular solution posts and solution posts posted as replies have the same structure.

3. It's possible to atomically edit any Solution post properties.

4. The contract data integrity is preserved after the corresponding migration.

5. For all the preexisting solution posts, the missing fields should be populated with blank values.

6. All blocked ticket display features implemented in https://github.com/near/neardevhub-widgets/issues/250 should be available on the front end.

**Comment by carina-akaia** [comment]
@ori-near I encountered some time-consuming difficulties with updating the post editing code because of its implementation details. I would like to add 3 more days to the estimation because I believe it's the amount of time needed to finish and test everything

**Comment by ori-near** [comment]
Hi @carina-akaia – can you please sidebar with @ailisp today to align on this ticket, your progress so far, and some of the difficulties you encounters? Just want to see if he can give any guidance to help unblock and reduce the complexity.

**Comment by carina-akaia** [comment]
@ori-near okay!
