### ISSUE TITLE
Set a new root for DevHub App

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#294]
This is the first in a series of refactors to make DevHub more modular, composable, and easy to contribute to.

Currently, DevHub is structured as such:

![Image](https://github.com/near/neardevhub-widgets/assets/16282460/00f65e92-b28d-4e9e-8444-df39a2520454)

In this setup, there are a few things to notice:
1. all widgets are under a "gigs-board" namespace
2. The homepage is situated within this namespace at : devgovgigs.near/widget/gigs-board.pages.Feed
3. Due to this namespace, we utilize a widget function which redirects within the namespace:
```javascript
function widget(widgetName, widgetProps, key) {
  widgetProps = {
    ...widgetProps,
    nearDevGovGigsContractAccountId: props.nearDevGovGigsContractAccountId,
    nearDevGovGigsWidgetsAccountId: props.nearDevGovGigsWidgetsAccountId,
    referral: props.referral,
  };

  return (
    <Widget
      src={`${nearDevGovGigsWidgetsAccountId}/widget/gigs-board.${widgetName}`}
      props={widgetProps}
      key={key}
    />
  );
}
```
4.  And we take props to determine the contract to use and widget source to use:
```javascript
const nearDevGovGigsContractAccountId =
  props.nearDevGovGigsContractAccountId ||
  (context.widgetSrc ?? "devgovgigs.near").split("/", 1)[0];

const nearDevGovGigsWidgetsAccountId =
  props.nearDevGovGigsWidgetsAccountId ||
  (context.widgetSrc ?? "devgovgigs.near").split("/", 1)[0];
```
5. We use an href function to handle redirects and links within the namespace:
```javascript
function href(widgetName, linkProps) {
  linkProps = { ...linkProps };

  if (props.nearDevGovGigsContractAccountId) {
    linkProps.nearDevGovGigsContractAccountId =
      props.nearDevGovGigsContractAccountId;
  }

  if (props.nearDevGovGigsWidgetsAccountId) {
    linkProps.nearDevGovGigsWidgetsAccountId =
      props.nearDevGovGigsWidgetsAccountId;
  }

  if (props.referral) {
    linkProps.referral = props.referral;
  }

  const linkPropsQuery = Object.entries(linkProps)
    .filter(([_key, nullable]) => (nullable ?? null) !== null)
    .map(([key, value]) => `${key}=${value}`)
    .join("&");

  return `/#/${nearDevGovGigsWidgetsAccountId}/widget/gigs-board.pages.${widgetName}${
    linkPropsQuery ? "?" : ""
  }${linkPropsQuery}`;
}
```

This leads to a lot of duplicated code at the top of each file, inefficiencies/unclarity when routing between pages, and general confusion regarding the purpose of the namespace and the files within it.

Not to mention that without a root, we are also unable to pass fonts and styles to the children which is not ideal.

To fix this, we can do the following:

1. Establish a new namespace. I propose "DevHub".
2. Place a homepage inside of this namespace; this determines the link that people should remember when writing widgets.
I like either "devgovgigs.near/widget/DevHub" or "devgovgigs.near/widget/DevHub.App". The only issue with /DevHub (without .App) is that the root file itself will not be situated inside the repository correctly, since we use the folder structure to determine names (DevHub/App = DevHub.App). If it is simply DevHub, then the file will not appear in the DevHub directory.... (although we can solve this in our build script. A potential solution could utilize the bos.config.json where we designate a root or introduce an "ignore path" flag. This way DevHub can be in the /DevHub directory, but not appear as DevHub.DevHub.)

3. Not only does the widget function hurt code readability and force us to stay within the gigs-board namespace (meaning that we cannot utilize the composable nature of BOS), but it also means that DevHub's dependencies are impossible to explore in WidgetSrc. See [the Feed](https://near.social/mob.near/widget/WidgetSource?src=devgovgigs.near/widget/gigs-board.pages.Feed); you'll see there are 4 distinct widgets inside of it, but none of them show up as Dependencies. On the contrary, see [Near Social homepage](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/N). See all the dependencies at the bottom?

![Image](https://github.com/near/neardevhub-widgets/assets/16282460/57eca3ff-75b2-46b3-8eba-71fa6a787a77)

4. Recursively passing in props for determining the widget and contract sources was really intuitive at the time and its helpful when showing a demo for PRs or testing your own contract. Although I don't think we need to pass this in via props; I think we can utilize a bos.config.json for storing the appAccountId and contractAccountId, which get injected at build time. This still has the benefits of being able to test with own contract or widgets, as well as deploy with the fields injected without needing to prop drill. 

5. For smooth routing, we should be using React Router <Link /> rather than <a /> for smoother page transitions and less re-renders. With a new root, we no longer have to determine the link to navigate to. We could maintain this function as it is helpful for turning a parameters object into a URL, but then we should move it to its own module and offer it to the community.

**Comment by elliotBraem** [comment]
To get it started, I've created a new namespace called "DevHub" and established a root at "DevHub.App".

Locked at this commit, 
View the demo [here](https://test.near.org/1.devhub.efiz.testnet/widget/DevHub.App).
View the code [here](https://github.com/elliotBraem/neardevhub-widgets/tree/625dcec79942ff7d7d7c7a59607690b954bbd44d/src/DevHub) 


## New Routes
With this setup, the point of entry is 1.devhub.efiz.testnet/widget/DevHub.App. 
Pages are navigated to via the "page" parameter, for the following route conversions:

devgovgigs.near/widget/gigs-board.pages.communities -> [devgovgigs.near/widget/DevHub.App?page=communities](https://test.near.org/1.devhub.efiz.testnet/widget/DevHub.App?page=communities)
devgovgigs.near/widget/gigs-board.pages.community.activity?handle=elliot -> [devgovgigs.near/widget/DevHub.App?page=community&handle=elliot](https://test.near.org/1.devhub.efiz.testnet/widget/DevHub.App?page=community&handle=elliot)
devgovgigs.near/widget/gigs-board.pages.Feed -> [devgovgigs.near/widget/DevHub.App?page=feed](https://test.near.org/1.devhub.efiz.testnet/widget/DevHub.App?page=feed)


## Theming
We have a root theme where can define global styles, such as the AttractableDiv that used to be included in build script:

```javascript
const Theme = styled.div`
  a {
    color: inherit;
  }

  .attractable {
    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !important;
    transition: box-shadow 0.6s;

    &:hover {
      box-shadow: 0 0.5rem 1rem rgba(0, 0, 0, 0.15) !important;
    }
  }
`;
```


## Smoother Navigation
Pages navigated smoother utilizing the <Link /> component (click Communities in navbar, click a community card, click DevHub logo. There are no full page refreshes)


## "Included" Code are now Modules
I have also moved the "included" code such as the contract methods and Struct to be their own modules which get imported like this:

```javascript
const { useQuery } = VM.require(`${nearDevGovGigsWidgetsAccountId}/widget/DevHub.modules.contract-sdk`);
const { Struct } = VM.require(`${nearDevGovGigsWidgetsAccountId}/widget/DevHub.modules.Struct`);
```

Now these can be reused by other projects.

## Remaining Prop Drilling Issue 
I am still maintaining the prop drilling for the widget account and contract account, but we can replace this using the [bos-workspace](https://github.com/NEARBuilders/bos-workspace/tree/dev) build script that does variable injection by NETWORK_ID environment variable. This will enable us to deploy to testnet on Dev as well. But for this reason, the refactor's dependencies still [do not show up](https://test.near.social/eugenethedream/widget/WidgetSource?src=1.devhub.efiz.testnet/widget/DevHub.App).

```javascript
const { page, nearDevGovGigsWidgetsAccountId, nearDevGovGigsContractAccountId, ...passProps } = props;

if (!nearDevGovGigsWidgetsAccountId) {
  nearDevGovGigsWidgetsAccountId = "1.devhub.efiz.testnet";
}
if (!nearDevGovGigsContractAccountId) {
  nearDevGovGigsContractAccountId = "thomaspreview.testnet";
}
```

## Next Steps

* To keep down scope, I'll create a separate story for solving the prop-drilling issue. I have local code that fixes it and will push that there.
* Refactoring the rest of Communities to close out the Epic
* Starting the conversation for establishing the component library

**Comment by ailisp** [comment]
Nice! I like your proposed steps and it will significantly improve our project structure and code reuse!
