### ISSUE TITLE
Updates to app-layout and app-header components to incorporate new design

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#295]
## Background
The App layout [component](https://near.social/devgovgigs.near/widget/gigs-board.components.template.app-layout) currently works as a reusable app layout that we use for most pages on Devhub. App layout page consists of a "header", "banner" and "children" component as its child components. Header is a fixed [component](https://near.social/devgovgigs.near/widget/gigs-board.components.organism.app-header) where as banner and children are passed from the parent component. 

This lets developers use app layout to use custom banners and children for specific pages while keeping the header same.

## Problem
The new homepage design needs updates to the App layout and App header component to incorporate the new designs according to the Figma file attached.

## User Stories

- [ ] As a devhub developer, working on building Devhub, I need an app-layout component which is resusable across different pages and is aligned with the new design.
- [ ] As a devhub developer, working on building Devhub, I need an app-header component which is a part of the new app-layout which is resusable across different pages and is aligned with the new design.
- [ ] As a devhub developer, working on building Devhub, I should be able to pass custom banner and children to the app-layout component.
- [ ] As a devhub user, I want to see the consistent app header across all devhub pages which is aligned with new design guidelines.

## Assets

Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=530-28&mode=design&t=Me9uGq2B4d5nZFly-4)

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by jaswinder6991** [comment]
Resolved as a part of #335
