### ISSUE TITLE
Create a section for NEAR Protocol information and ecosystem link

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#296]
## Problem
The current Devhub homepage does not have a section for new developers to know what NEAR is. This makes it difficult for them to get an introduction to NEAR and its ecosystem. This adds confusion to their journey on Devhub.

## User Stories
- As a developer, I want to know what NEAR is in a precise Introduction section.
- As a developer, I want to see links where I can read more about NEAR's tech and its ecosystem.

## Acceptance Criteria

- [ ] Create a section with quick introductory facts about NEAR to catch developer's attention.
- [ ] Provide short description for each fact and provide additional links to more resources.
- [ ] Provide a link to NEAR's ecosystem to check other projects on NEAR.
- [ ] Follow the figma designs attached below.

## Assets

Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1248&mode=design&t=QfZzsUC8hiE6i5Sl-4)
Copy - As mentioned in the designs

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325

**Comment by jaswinder6991** [comment]
Resolved by #335 (merged to main)
