### ISSUE TITLE
Set the "nearDevGovGigsWidgetsAccountId" at build time

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#301]
**Is your feature request related to a problem? Please describe.**

In our code, we prop drill "nearDevGovGigsWidgetsAccountId" so that we can programmatically replace the source of our widgets.

This means we have code that looks like this at the top of each of our files, and we use a specific "widget" function to determine the path:
```javascript
const nearDevGovGigsContractAccountId =
  props.nearDevGovGigsContractAccountId ||
  (context.widgetSrc ?? "devgovgigs.near").split("/", 1)[0];

const nearDevGovGigsWidgetsAccountId =
  props.nearDevGovGigsWidgetsAccountId ||
  (context.widgetSrc ?? "devgovgigs.near").split("/", 1)[0];

function widget(widgetName, widgetProps, key) {
  widgetProps = {
    ...widgetProps,
    nearDevGovGigsContractAccountId: props.nearDevGovGigsContractAccountId,
    nearDevGovGigsWidgetsAccountId: props.nearDevGovGigsWidgetsAccountId,
    referral: props.referral,
  };

  return (
    <Widget
      src={`${nearDevGovGigsWidgetsAccountId}/widget/gigs-board.${widgetName}`}
      props={widgetProps}
      key={key}
    />
  );
}
``` 

During #294, this has been replaced with <Widget so that it can be picked up by dependencies when a BOS user views the widget source of our components. However, still having this be determined on run time does not fix the issue.

```javascript
const { data, onSubmit, nearDevGovGigsWidgetsAccountId } = props;

<Widget
    src={`${nearDevGovGigsWidgetsAccountId}/widget/DevHub.components.organism.Configurator`}
    props={{
      externalState: data,
      schema: CommunityAboutSchema,
      onSubmit: onSubmit,
      nearDevGovGigsWidgetsAccountId
    }}
  />
```

DevHub's dependencies are impossible to explore in WidgetSource. See [the Feed](https://near.social/mob.near/widget/WidgetSource?src=devgovgigs.near/widget/gigs-board.pages.Feed); you'll see there are 4 distinct widgets inside of it, but none of them show up as Dependencies. On the contrary, see [Near Social homepage](https://near.social/mob.near/widget/WidgetSource?src=mob.near/widget/N). See all the dependencies at the bottom?

**Describe the solution you'd like**

Setting the nearDevGovGigsWidgetsAccountId at build time with a simple string replace and a config file would not only solve the above issue, but enable us to configure different widget srcs for mainnet and testnet, as well as set up github actions to deploy to the separate environments as well.

**Describe alternatives you've considered**

This implementation exists in [bos-workspace](https://github.com/sekaiking/bos-workspace). See the appAccountId and how there is a script that goes through and replaces "/*__@appAccountId*/" with the value specified in bos.config.json.

I have forked this workspace and made modifications [here](https://github.com/NEARBuilders/bos-workspace/tree/dev) so that it can check a NETWORK_ID variable as well before determining the value to apply.

**Additional context**

**This story requires that we no longer serve our widgets from /src, but instead add a build step to serve the transpiled code from /build**

**Comment by jaswinder6991** [comment]
Hi @elliotBraem, given the refactor for the revamp. I am assuming this addressed for now. Can we close this ticket with a comment on the solution?

**Comment by elliotBraem** [comment]
Yep! Closing.
