### ISSUE TITLE
Create an additional banner for the communities and the activity feed page

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#302]
## Problem

Some sub pages on Devhub like the Feed and the All Communities page and possibly more have banner/hero section in the app layout that are not aligned with the new brand guidelines. 

## User Stories
- As a developer visiting the Devhub sub paged as mentioned above, I want to experience a cohesive design.
- As a developer, I expect the banner section on sub pages to have a compelling design and copy that aligns with the new brand design of Devhub and explains

## Acceptance Criteria

- [ ]  The additional banner section should have an updated visual design in line with the new brand design.

## Assets

Copy - As mentioned in the Figma
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=535-333&mode=design&t=TXCpbGCKUR4UdgeB-4)

**Comment by itexpert120** [comment]
Can you assign this to me?

**Comment by itexpert120** [comment]
Requested merge: https://github.com/near/neardevhub-widgets/pull/325

**Comment by jaswinder6991** [comment]
Resolved by #335
