### ISSUE TITLE
Create a new homepage for Devhub that has the newly designed sections and a new route.

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#303]
## Background

As part of the Devhub homepage revamp, we have created new [designs](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=530-15&mode=design&t=TXCpbGCKUR4UdgeB-4) for the homepage. We have created different tickets for different sections of the homepage to be developed as individual BOS widgets. Embracing the modular development philosophy, it is best to have different sections as independent widgets so they can be reused. 

Given all these section would be different widget, we need a homepage widget which can use all these different section widgets to make the final homepage like shown in the Figma designs above.

## Acceptance Criteria

- [ ] Create a Homepage widget that has all the different sub section widgets in it.
- [ ] Create a new route for the homepage. Currently there is no homepage widget, hence we need a new route for the new widget.
- [ ] Change the [MyPage](https://near.social/mob.near/widget/MyPage) setting to make homepage the new _MyPage_.

## Assets
[Figma](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=648-1103&mode=design&t=QfZzsUC8hiE6i5Sl-4)

**Comment by elliotBraem** [comment]
See #306, this would make a homepage route at devgovgigs.near/widget/DevHub.App
