### ISSUE TITLE
Near Dev Hub is not responsive on mobile screens

### ISSUE THREAD

**Issue by Rishabhraghwendra18** [near/neardevhub-widgets#310]
**Describe the bug**
[neardevhub.org](https://neardevhub.org/) is not responsive as shown below 
![WhatsApp Image 2023-10-17 at 12 53 46 PM](https://github.com/near/neardevhub-widgets/assets/43534227/86989a3b-7f21-46e3-a487-f4e172321b70) 

**To Reproduce**
1. Go to [neardevhub.org](https://neardevhub.org/) on mobile screen

**Expected behavior**
Should be mobile responsive

**Smartphone (please complete the following information):**
 - Device: Realme 5G Pro
 - Browser: Google Chrome

**Comment by jaswinder6991** [comment]
As a part of the new release we have worked on mobile responsiveness. Some of the subpages need a little bit more work. Will revisit them with dedicated tickets.
