### ISSUE TITLE
Community pages showing all posts

### ISSUE THREAD

**Issue by PiVortex** [near/neardevhub-widgets#314]
**Describe the bug**
Under the community pages, under activity, all posts are showing,

**To Reproduce**
1. Go to any community pages [for example](https://near.social/devgovgigs.near/widget/gigs-board.pages.community.activity?handle=component-libraries)
2. Go to activity, look in the list
3. See all posts

**Expected behaviour**
Only posts made under the community or tagged with the community should be shown here 

**Screenshots**
![image](https://github.com/near/neardevhub-widgets/assets/124691791/9635e8fe-ed65-4640-bba7-cff4f4f08730)
Component libraries but near campus is showing

**Desktop (please complete the following information):**
OS: Windows 11
Browser: Chrome

**Comment by ori-near** [comment]
Thanks @PiVortex for reporting this. Confirming that I reproduced this.
