### ISSUE TITLE
Mobile responsive design for the new Devhub Homepage

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#354]
**Is your feature request related to a problem? Please describe.**
A mobile responsive design for the new homepage revamp.

**Describe the solution you'd like**
The new devhub homepage should work on mobile screen size along with the desktop size.

**Assets**
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=920-724&mode=design&t=LWn9zMnMIf4u3Z92-4)

**Comment by itexpert120** [comment]
Assign this to me

**Comment by abitsalihu** [comment]
Hey @jaswinder6991 , I would love to work on this. :)

**Comment by jaswinder6991** [comment]
Hi @abitsalihu, Zeeshan already started working on this. Apologies for the delay in response.

**Comment by jaswinder6991** [comment]
Resolved by #417 and #427
