### ISSUE TITLE
Create an About Page to describe Devhub in detail.

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#355]
## Problem
Currently users often struggle to understand what Devhub is and what role it plays in the NEAR Ecosystem. Part of the reason behind the whole revamp has been to solve this problem. On the newly designed homepage we have sections on different things we do and manage at Devhub but there is no dedicated page that Describes what Devhub is in depth. 

## User Stories
As a developer visiting the Devhub homepage, I want to understand what Devhub is and its role in the NEAR Ecosystem.
As a developer, I want to redirect to a dedicated About page to know more about Devhub. 

## Acceptance Criteria
- [ ] A dedicated About page with details about Devhub.
- [ ] An option in the main nav menu to redirect to the About Page

Copy - As mentioned in the Figma
Figma - [Link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=328-472&mode=design&t=LWn9zMnMIf4u3Z92-4)

**Comment by itexpert120** [comment]
Assign this to me

**Comment by jaswinder6991** [comment]
Resolved by #351
