### ISSUE TITLE
Blog posts should not appear in Activity feeds

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#376]
**Describe the bug**

The new #268 blog plugin's blog should not appear in the main Activity feed or any community Activity feed. They should be exclusive to the community's blog plugin.

You can reference devhub.entity.addon.blog.Viewer and it's child devhub.entity.addon.blog.Feed for how to include/exclude labels; this needs to be modified in feature.post-search.panel -- Or panel should sit on top of this shared Feed component.

**Acceptance Criteria**

- [ ] Blogs do not show up in main feed
- [ ] Blogs do not show up in a community activity feed

**Additional Context**

Blogs are of post_type "Comment", have parent_id === null, and have the "blog" label

**Comment by petersalomonsen** [comment]
Just adding some description to the issue.

This blog post here is currently showing in the feed, but it should not.
https://near.social/devgovgigs.near/widget/app?page=feed

<img width="1006" alt="image" src="https://github.com/near/neardevhub-widgets/assets/9760441/fdd1e332-c1f1-4020-a3df-20b4ad9001f8">
