### ISSUE TITLE
Add metadata to new app root

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#378]
We need to modify the metadata for the [core widget](https://near.org/near/widget/ComponentDetailsPage?src=devgovgigs.near/widget/app).

![Screenshot 2023-10-31 at 11 53 16 PM](https://github.com/near/neardevhub-widgets/assets/16282460/f3c2387e-90db-4b02-b1a9-dc0242645648)

We need:

name,
description (will be under README),
image

@ori-near what should we use?

**Comment by frol** [comment]
@elliotBraem Didn't we agree that we won't use `app` component and instead pages will be individual components?

1. We should only set the metadata for the components we will deploy to the new `devhub.near` account (I am setting it up)
2. Can we quickly migrate away from `app` as we discussed before?

**Comment by jaswinder6991** [comment]
The metadata for the main [app](https://near.social/devhub.near/widget/app) has been edited.
