### ISSUE TITLE
10/31 Alpha Testing – Homepage Feedback

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#380]
I tested the latest preview version on mainnet that Elliot shared. I'm capturing feedback for the homepage here. Adding 🔴 for any critical items.

# Homepage Feedback Round 1

1. **Navigation Profile Image:** Change the green profile image to the user's image.
2. **Hero Button:** Change the hover from text underline decoration to background #151515 and color #F4F4F4 and no underline:
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/7a30b742-09c6-48a9-a22b-e6e8441228f4)
3. **Explore Section Copy Size:** Change the copy font size from 1.25rem to 1rem, as it looks too big. ![Image](https://github.com/near/neardevhub-widgets/assets/110252255/aa09cb1d-39d2-484d-841d-3c2a246e0b8f)
4. 🔴 **Explore Section Copy Color:** Change the text instances from light green color (#rgb(0, 236, 151)) to a darker #04A46E (e.g. /explore + the title and learn more for each stat), as it is hard to read the light green text against gray/white background.
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/129d81ec-6f03-4811-8ab9-31586489efbe)
5. **Explore Section Button:** Add a hover background color #04A46E.
6. **Featured Communities Cards:** It would be great to tweak the look/feel of each card to make it a bit smaller (e.g. on desktop: padding 1.5rem, gap .5rem, font-size for title 1.5rem) 
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/19830141-1d93-42aa-a2b9-bfa55a08e76b)
7. 🔴 **Featured Communities Copy Changes:** Change "/dev/hub Hacks" to "DevHub Hacks". Change "DevDAO Fellowship Program" to "NEAR Platform Fellowship"
8. 🔴 **Participate Copy:** Change the text instances from light green color (#rgb(0, 236, 151)) to a darker #04A46E (e.g. /participate + the number and circle around it), as it is hard to read the light green text against gray/white background. Change the hover from text underline decoration to color #096D50 and no underline:
9. **Participate Button:** Add a hover background color #04A46E and no underline.
10. **Get Funding:** Change link of learn more to https://near.social/devgovgigs.near/widget/app?page=community&handle=developer-dao&tab=Funding
11. 🔴 **Newsletter:** Unable to subscribe. I enter email, click subscribe, and nothing happens.
12. 🔴 **Footer Links:** Unable to open any of the links. They should all open in a new tab.
13. **Footer Twitter Icon:** Change Twitter logo to the new X one.

**Comment by jaswinder6991** [comment]
I have submitted a [PR](https://github.com/near/neardevhub-widgets/pull/377) for the following changes:

1. @itexpert120 could you do it.
2. Done.
3. Done.
4. Done.
5. Done. However @ori-near, I think default background: #04A46E and black on hover looks better. Let me know what you think.
6. Done.
7. Done.
8. Done.
9. Done. Hover color done, I could not remove the underline though. @itexpert120 can you check please, same code works everywhere lese but not here.
10. Done.
11. The new changes, removes the Input field and has only "Subscribe" button, that takes you to a shardog page to sign up for the newsletter. Will fix this when I get the shardog link, should be today.
12. Done.
13. Done. I don't like the [version](https://logowik.com/twitter-x-logo-vector-59293.html) I used though. I like [this](https://logowik.com/twitter-x-icon-logo-vector-59294.html) better but svg for this has some additional tags that does not work on bos. @itexpert120 could you try this too, try if you can use [this](https://logowik.com/twitter-x-icon-logo-vector-59294.html) logo.

**Comment by ori-near** [comment]
Thank you @jaswinder6991! 

**For #5** – sounds good, let's try that (#04A46E green background with the hover of #151515 background and color #F4F4F4). It would be great if you can also apply this same color to copy & buttons on light background on the other pages. 

Example, community:
![Screenshot 2023-11-01 at 8 09 41 AM](https://github.com/near/neardevhub-widgets/assets/110252255/4fdb46db-46e7-4c2b-8c5d-bdf7a800b194)

Example, activity:
![Screenshot 2023-11-01 at 8 10 49 AM](https://github.com/near/neardevhub-widgets/assets/110252255/60067366-f45d-42a3-87c3-1ebfdf7313c1)

**For #11** – Can you please add the same button color scheme from the hero? Again, all buttons should be consistent across the site. Please also look at border radius, as I noticed some inconsistencies on other pages.

Thanks again!

**Comment by itexpert120** [comment]
I will fix the remaining issues @jaswinder6991

**Comment by itexpert120** [comment]
Check: https://github.com/near/neardevhub-widgets/pull/412
