### ISSUE TITLE
10/31 Alpha Testing – Widgets Framework & Wiki Page Feedback

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#381]
I tested the latest preview version on mainnet that Elliot shared. I'm capturing feedback for the widgets framework & wiki page here. Adding 🔴 for any critical items.

# Feedback Round 1

## Configure Community Settings Page

1. 🔴 **Editing Add-Ons:** When I click Edit, I don't see what I should do as a next step. Can we show the dropdown?
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/683e5c45-bbc3-4b98-b2cd-99077c0a6b0e) 

2. 🔴 **Editing Add-Ons:** I clicked around and managed to find the hidden dropdown, but it overlaps over the delete button. Can we make sure it's easy to see all the fields?
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/e3fe16e0-9285-47df-b8b5-553c5e72dd9c) 

3.  **Editing Add-Ons:** Once I click the green plus button, it adds the widget I selected, but then it highlight that widget again in the second line, which is confusing. Can we show the dropdown again without anything preselected?
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/4f751917-49c3-4cb0-adc7-d392535670de)

4.  **Editing Add-Ons:** The order column is confusing when only one widget is selected. Could we still show the arrow and just make it un-clickable?

## Wiki Widget

1. 🔴 **Editing Page:** When I open the new wiki page,  I see "No Wiki Configured." I click configure icon, entered all the fields (Title, Description, Content) and click publish. I confirm and approve transaction. And then I see the no Wiki Configured page again. I click settings again but and see the changes, but unable to see them on the page.

2. 🔴 **Editing Page Preview:** When I click Preview in the configure wiki setting page, I see "No Wiki Configured" message. 

3. **Editing Page:** Can we change Description to Subtitle. And Then add a Page Content field above the big text area?

**Comment by elliotBraem** [comment]
Addressed all of the above in #382

**Comment by jaswinder6991** [comment]
Don't want to add this as a priority and maybe it is better to open a separate ticket for this but we need guidelines for buttons which are consistent across the whole site.
