### ISSUE TITLE
Newsletter form is not rendered nicely

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#384]
**Describe the bug**

<img width="841" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/81e780fb-0b1a-460b-8d86-08da14c12786">

**To Reproduce**
1. Go to https://near.social/devgovgigs.near/widget/app
2. Scroll down to 'Newsletter'

**Comment by ori-near** [comment]
Thanks for writing this @frol. Also captured this in https://github.com/near/neardevhub-widgets/issues/380#issue-1971696822. @jaswinder6991 ended up having to create a workaround and just link to an external newsletter. So closing this.
