### ISSUE TITLE
Direct post link in the new version does not have the general DevHub layout

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#386]
**Describe the bug**

When you open a post by a direct link: https://near.org/devgovgigs.near/widget/devhub.entity.post.Post?id=1959, there is no way to understand that it is DevHub, and impossible to navigate to the rest of DevHub.

Just for comparison, here is the old link: https://near.social/devgovgigs.near/widget/gigs-board.pages.Post?id=1959 (notice there is a top navigation bar)

**Expected behavior**

The link should point to a "page" component, not the internally reusable component.

**Screenshots**

<img width="1364" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/a6fe7a7f-aefd-46a7-8620-244087ed4321">

vs old and functional:

<img width="1368" alt="image" src="https://github.com/near/neardevhub-widgets/assets/304265/f0903fdd-cc2d-4596-a6f6-032408c0532b">

**Comment by itexpert120** [comment]
@elliotBraem Should we create  new page in app.jsx for this? So we can wrap the Post Component in AppLayout
