### ISSUE TITLE
Background color does not match the design

### ISSUE THREAD

**Issue by frol** [near/neardevhub-widgets#387]
**Describe the bug**

https://github.com/near/neardevhub-widgets/blob/37f3fd9f4add94584c3a20ef962194d22aef950d/src/devhub/components/templates/AppLayout.jsx#L8

I believe it has to be `#f4f4f4`, and it looks better with this color than the current one.

**To Reproduce**
1. Go to https://neardevhub.org
2. Notice that the background does not match the design

**Comment by itexpert120** [comment]
Resolved in https://github.com/near/neardevhub-widgets/pull/393
