### ISSUE TITLE
Users should not be able to create posts with blog label outside of Blog plugin

### ISSUE THREAD

**Issue by elliotBraem** [near/neardevhub-widgets#391]
**Describe the bug**

We must not allow users to create blogs outside of the blog plugin. Modify the create post page to not allow "blog" as an eligible label.

**Acceptance Criteria**

- [ ] Users cannot create posts with label "blog" from the create page

**Comment by jaswinder6991** [comment]
When someone tries the blog tag, should we show a tooltip or a small popup, saying "Blog is a reserved keyword."?
@elliotBraem @ori-near

**Comment by jaswinder6991** [comment]
Making it P0 because we don't want a lot of users creating posts on the main feed with Blog tag which affect the Blog feed later (having to manually exclude this not well formed blogs via simple posts.)

**Comment by ori-near** [comment]
Hi @jaswinder6991 / @elliotBraem – what's the solution that you ended up implementing here? I once outlined some requirements for protected labels in https://github.com/near/neardevhub-widgets/issues/10. We may need to revisit this, as right now it's unclear which labels are protected.
