### ISSUE TITLE
Bug: Markdown on Wiki pages is not correctly adding hyperlinks

### ISSUE THREAD

**Issue by bearmans** [near/neardevhub-widgets#398]
The new Wiki addon Markdown rendering currently does not seem to be rendering links:

Old:
![image](https://github.com/near/neardevhub-widgets/assets/100602774/b77f4f8f-8b6d-4b4f-bd37-336c3961364e)

New:
![image](https://github.com/near/neardevhub-widgets/assets/100602774/fd9a7199-4b8c-46d3-969f-c441d908bf90)

However, the data migration did correctly import the links as they already exist on the old site:
![image](https://github.com/near/neardevhub-widgets/assets/100602774/1b119616-e71d-4be7-bab9-fa1efa5a6ea5)

So this appears to be an issue with the Markdown renderer itself- not sure if this is a component issue or a VM issue.

**Comment by jaswinder6991** [comment]
@elliotBraem, can you help with this?
