### ISSUE TITLE
Wiki page "Title" and "Description" formatting

### ISSUE THREAD

**Issue by bearmans** [near/neardevhub-widgets#399]
Currently in the new site, inputting the "Title" and "Overview" fields in the Wiki editor like so:

![image](https://github.com/near/neardevhub-widgets/assets/100602774/640f9bd8-7722-476c-81b1-83937cef3a19)

Just results in them being appended to the top of the main md content like so: 

![image](https://github.com/near/neardevhub-widgets/assets/100602774/4e173261-d8bc-4ebf-b071-74574d694ea7)

This isn't particularly attractive and also doesn't serve much purpose as the title and description don't end up anywhere on the page other than the main content. Ideally, Title & Description should be separate & prominent from the main body, and "Title" should also become the "Name" of the Wiki page as it did on the old page:

Old:
![image](https://github.com/near/neardevhub-widgets/assets/100602774/42b2eb26-92d4-43e3-b392-b210a54e7444)

Current:
![image](https://github.com/near/neardevhub-widgets/assets/100602774/c3618dd7-a94e-40f1-90ca-824b77cdd0d8)

**Comment by ori-near** [comment]
Thanks for posting this @bearmans. I think we can follow the same title/subtitle design from the blog widget.

**Comment by elliotBraem** [comment]
@ori-near Is this how Wiki should be? 

Right now with the add-on framework, we have tab names -- and then the Wiki has it's own title, subtitle, and content. I hadn't been considering the Title to be equal to the tab name, but maybe it should? 

It's not a heavy lift to make it happen, but would like to confirm this before implementing as it does break the pattern.

**Comment by elliotBraem** [comment]
For more context,

@bearmans, you can configure the Addon tab name in "Configure Community". See below.

<img width="962" alt="Screenshot 2023-11-02 at 11 22 15 AM" src="https://github.com/near/neardevhub-widgets/assets/16282460/24f755f4-0c97-4f6a-8836-56cbe61399dd">
