### ISSUE TITLE
11/01 Alpha Testing – Posts

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#405]
Capturing feedback for the post (that appears in both the activity feed and communities). Adding 🔴 for any critical items. I spoke with @itexpert120, who said he can work on these asap.

# Posts Feedback Round 1

1. 🔴 **Missing Share Link:** The Figma designed did not include the share link. But this was a critical oversight – because currently users do not have a way to open posts or get the link for them. Please add the share link right next to the version history and make sure that the new formatting also applies to open posts.
![Screenshot 2023-11-01 at 5 40 51 PM](https://github.com/near/neardevhub-widgets/assets/110252255/ca0ab4cb-61f2-4d6c-bc0a-aa0d8309ecfe)

2. **Card Title:** The card title looks too big for some posts:
![Screenshot 2023-11-01 at 5 45 34 PM](https://github.com/near/neardevhub-widgets/assets/110252255/b7fd58ea-bc19-40fb-b2e1-bee42b7d89e4)
Can we reduce the size to 1.15rem? 

Also, the icon for each post type feels a bit out of place. Can we move it to align left with the rest of the content? 

3. **Mobile View:** The Figma designs did not include mobile view for posts. But it would be great if we can make sure the text fits/renders on mobile better. We can fine tune it later. 
![Screenshot 2023-11-01 at 5 49 48 PM](https://github.com/near/neardevhub-widgets/assets/110252255/791ed912-25ab-406c-ad6b-6721ca99d9f7)

**Comment by itexpert120** [comment]
Assign this to me @jaswinder6991

**Comment by jaswinder6991** [comment]
![Image](https://github.com/near/neardevhub-widgets/assets/12672862/1775483b-8b2f-46c2-85dd-e1d75cc28304)

I think the header(Profile name and handle, date time on right side) of the old design was better, can we just do that. 
We can do tags as they are done in the new designs but last post view looked perfectly fine to me. 
@itexpert120

**Comment by itexpert120** [comment]
Sure, we can do that

**Comment by itexpert120** [comment]
@jaswinder6991 done
