### ISSUE TITLE
Community Page should not include the tag/post bar on all tabs except for the activity one

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#406]
Currently, every tab/widget on communities includes the required tag + post button:
![Screenshot 2023-11-01 at 5 54 33 PM](https://github.com/near/neardevhub-widgets/assets/110252255/4d6a2e26-23bc-44aa-b37f-b6d2e9e38458)

However, only the activity (homepage) tab contains that. All other tabs should look like this:
![Screenshot 2023-11-01 at 5 57 32 PM](https://github.com/near/neardevhub-widgets/assets/110252255/39d9f2b2-6ea8-4daf-b12f-a5f15e218b98)

**Comment by jaswinder6991** [comment]
Thanks @ori-near for pointing this out. I try to edit the Figma to help this align better.
Here is a [link](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=1458-29&mode=design&t=tg7tKPadA3KtsmCW-4) for the Activity Tab and here is another [tab](https://www.figma.com/file/fkxdNelmOyoxcQIH36TfP8/%2Fdev%2Fhub.near-public?type=design&node-id=1576-348&mode=design&t=tg7tKPadA3KtsmCW-4) (used blog for example.).

**Comment by itexpert120** [comment]
Assign this to me @jaswinder6991

**Comment by itexpert120** [comment]
Done: https://github.com/near/neardevhub-widgets/pull/410

**Comment by itexpert120** [comment]
Done: https://github.com/near/neardevhub-widgets/pull/410
