### ISSUE TITLE
11/1 Alpha Testing - Blogs

### ISSUE THREAD

**Issue by bearmans** [near/neardevhub-widgets#407]
## Round 1 issues:

**Blog editor throwing "toLowerCase is not a function" error**

Currently, attempting to use the "editor" tab of the Blog addon results in an error:

![image](https://github.com/near/neardevhub-widgets/assets/100602774/bc748836-8451-493a-b823-47774165f4d2)

(https://near.org/devgovgigs.near/widget/app?page=community&handle=devhub-test&tab=Blog)

I don't believe it's possible to add a blog another way without directly interfacing with the contract, so it's challenging to do any additional testing as of yet.

**Comment by itexpert120** [comment]
Fixed in https://github.com/near/neardevhub-widgets/pull/409
