### ISSUE TITLE
Click on tag doesn't filter by tag any more

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#429]
**Describe the bug**

In feed page click on any post's tag, e.g. nearcon, the url bar will rewrite with `tag=nearcon`: https://near.org/bo.near/widget/app?page=feed&tag=nearcon, however app doesn't realize this props change and not cause a re-render. The re-render only happens after manually refresh the page.

**To Reproduce**
1. Go to activity feed page
2. Click on any tag of any post
3. The url changes, but page doesn't filter by the tag

**Expected behavior**
The page should filter by the tag

**Additional context**

Elliot and I have come up with some potential fixes, but I was not able to fix it in a good way. 

Elliot's thoughts:
> Elliot, [11/2/23 10:44 PM]
I’ve been trying to think about this and I don’t really know besides setting the tag in state and passing that as a prop
Elliot, [11/2/23 10:44 PM]
So linking but also changing state on click
Elliot, [11/3/23 12:45 AM]
Thinking more about it, it may be that we need to update a key on the div that matches the tag maybe. Or the query parameters as a whole. I'll try something out; thanks for bringing this up

Bo's attempts:
tried out but the link to a tag is a `<Link>`, It seems not possible to set the target widget's state with it. A way may work is to escalate tag props all the way up to the app widget, and pass a updateTag function all the way down to the post-search/panel.jsx. Then use props.tag instead of state.tag.

**Comment by Megha-Dev-19** [comment]
hey @ailisp  I just tried using `widgetSrc: "#/${REPL_DEVHUB}/widget/app",` adding `#` to rerender the page and it works
what do you think of the approach?

**Comment by Tguntenaar** [comment]
Hey @Megha-Dev-19, I believe the current solution might not be ideal. It could result in a less-than-optimal user experience, especially for those with slower internet connections.

https://github.com/near/neardevhub-widgets/assets/28901891/79e1c53d-1d40-4e81-b99d-b4796224368a

**Comment by Megha-Dev-19** [comment]
yeah I agree with you @Tguntenaar, but I did it as hot fix right now, since I faced the same issue (so others might be facing too)
We can create another ticket to optimise it. 
But if we plan to take the optimised code only then I will think of something better

**Comment by Tguntenaar** [comment]
@Megha-Dev-19 did you try adding a useEffect that fires when the query parameters change? That might work as well.

**Comment by itexpert120** [comment]
How about using <a> instead of <Link>?

**Comment by Tguntenaar** [comment]
@Megha-Dev-19 I've tested it and `useEffect` does not work as I had expected, also using the `<a>` tag has the same effect as a hashtag.

**Comment by Megha-Dev-19** [comment]
I see, I was going to test the useEffect today, thanks for letting me know @Tguntenaar

**Comment by Megha-Dev-19** [comment]
I got it working, but not sure if the solution is the best one
