### ISSUE TITLE
[Enhancements] Decommissioning use of legacy widgets in the new Devhub app

### ISSUE THREAD

**Issue by jaswinder6991** [near/neardevhub-widgets#461]
**Problem**
In the new Devhub app, we still reference/use some of the old gigs-board widgets hosted by devgovgigs.near account. 

**Solution**
Here are the different [files](https://github.com/search?q=repo%3Anear%2Fneardevhub-widgets%20REPL_DEVHUB_LEGACY&type=code) in the current project the refer to the old app's widget. We need to port them to the current Devhub app.

**Comment by itexpert120** [comment]
Would simply adding these widgets to new codebase and using them on new account be considered good?

**Comment by Megha-Dev-19** [comment]
@ori-near @jaswinder6991 I would like to take this ticket

**Comment by ori-near** [comment]
@Megha-Dev-19 now that you have access, feel free to pick up tickets and assign yourself to them! And ideally keep a work in progress limit of 1-2 max. Thank you.
