### ISSUE TITLE
Clicking on a user profile leads to error message

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#474]
**Describe the bug**
Clicking on a user profile icon or name from any page on DevHub leads to an error message.

**To Reproduce**
1. Go to the [activity feed](https://near.social/devhub.near/widget/app?page=feed)
2. Click on a user's profile image or name or user name
3. See `Source code for "devhub.near/widget/devhub.near/widget/ProfilePage" is not found` error message

**Expected behavior**
Clicking on a user's image should lead to their profile page.

**Screenshots**
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/e89276ab-d1f8-49d0-a482-e3b9dc8cce45)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browsers: Chrome & Safari
 - Version: Latest

**Comment by Megha-Dev-19** [comment]
@ori-near I would like to take this ticket

**Comment by ori-near** [comment]
Thanks @Megha-Dev-19! Assigned it to you.
