### ISSUE TITLE
Improve communities page rendering & sorting

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#481]
# Problem
Currently, we display 2 communities per row on the communities page. This makes it very difficult to see at a glance the variety of communities that exist. Additionally, the default sorting (e.g. recently created) does not indicate the sorting logic.

# Acceptance Criteria

- [ ] Display 3 communities per row on desktop on the communities page. Reduce the size as needed for smaller screen sizes.
- [ ] The sort button should say: "Sort: Latest"
  - [ ] Whichever sorting mechanism is enabled, the sort should still appear (E.g. Sort: Z-A) similar to the logic of the sort button on the activity feed

**Comment by Megha-Dev-19** [comment]
@ori-near I would like to take this ticket

**Comment by itexpert120** [comment]
I was actually working on this lol

**Comment by ori-near** [comment]
Looks great, thank you @itexpert120. BTW please make sure to assign yourself to ticket / indicate in the comment + move the ticket to in progress. That way people will know you are working on it.

**Comment by itexpert120** [comment]
Yeah, I'll keep that in mind
