### ISSUE TITLE
Introduce a consistent preview experience for posts / wiki

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#482]
# Problem
Currently, there is an inconsistent preview experience when creating various content types on DevHub. 

**Example 1: Posts**
The preview appears below what you're writing, which is hard to see. 

![Image](https://github.com/near/neardevhub-widgets/assets/110252255/82b2f7d4-4d62-491a-bcf7-3ec6afb9ca1c)

**Example 2: Wiki**
The preview appears as a separate tab:
![Image](https://github.com/near/neardevhub-widgets/assets/110252255/81a29d3d-8a95-421a-ae15-bf6c41583a49)

Also refer to the editing experience: 
https://github.com/near/neardevhub-widgets/issues/240

# User Story
As a user, I want to have a consistent editing experience on DevHub.

# Acceptance Criteria
[Need to flush this out after getting UX/design. But ideally we implement a consistent and similar write/preview tab experience to GitHub issues].

**Comment by itexpert120** [comment]
Proposed Changes:
- Tabbed UI for Post Creator
<img width="842" alt="image" src="https://github.com/near/neardevhub-widgets/assets/46527178/ad8784ab-2d9d-4d38-99cf-dcebb5104767">

- Tabbed UI for Post Editor
<img width="841" alt="image" src="https://github.com/near/neardevhub-widgets/assets/46527178/4a9eaa14-0829-4a90-b4a0-db05c25e5177">
