### ISSUE TITLE
Add a contributors section to our readme

### ISSUE THREAD

**Issue by ailisp** [near/neardevhub-widgets#506]
Similar to 
https://github.com/feature-sliced/documentation

**Comment by namrata18s** [comment]
can I work on this?

**Comment by DeleMike** [comment]
Hello @ailisp, I'm Michael.
I would like to work on this issue.

Any extra info I need apart from the link shared? 
Thanks.

**Comment by Tguntenaar** [comment]
Hi @DeleMike! 

I just assigned you to the ticket. You can read [this doc](https://github.com/near/neardevhub-widgets/blob/main/docs/how-we-work.md) on how we work for some extra info.

**Comment by DeleMike** [comment]
@Tguntenaar, thank you. I am working on it. 

I'm sorry, I was reading [this doc](https://github.com/near/neardevhub-widgets/blob/main/docs/how-we-work.md) and it mentioned how we have to move the issue to 'In Progress' when we are working an issue. I tried doing that and I mistakenly unassigned the issue. Can you reassign me? Also, how can I move the issue to 'In Progress'?

**Comment by Tguntenaar** [comment]
Hi @DeleMike, no worries I re-assigned you. I moved it to in progress for you. You can ask any of the contributors with permissions to do it.

**Comment by DeleMike** [comment]
Thank you! @Tguntenaar
