### ISSUE TITLE
Label missing error in post creation

### ISSUE THREAD

**Issue by Megha-Dev-19** [near/neardevhub-widgets#534]
Steps to reproduce:
1) Create a post [here](https://near.org/devhub.near/widget/app?page=create)
2) Don't add a label and proceed
![image](https://github.com/near/neardevhub-widgets/assets/100185149/22de4c07-ec72-4439-b3e2-ca213447bb66)

I think in UI we should add checks (about mandatory fields) before creating the txn

**Comment by itexpert120** [comment]
I created a post with no tags (using Meteor Wallet)
https://near.social/devhub.near/widget/app?page=post&id=2349
