### ISSUE TITLE
Deposit should be zero and gas should not exceed allowance or max gas for a transaction

### ISSUE THREAD

**Issue by petersalomonsen** [near/neardevhub-widgets#549]
**Is your feature request related to a problem? Please describe.**
For https://github.com/NearSocial/VM/pull/156 to work, and in order to solve #137 there cannot be any deposit or a gas amount that will trigger wallet redirection

**Describe the solution you'd like**
Deposit should be removed, and gas should not be more than `MAX_GAS` ( https://github.com/near/near-api-js/blob/858b8ee35ffc7d6409b3d72b01f59f4e117db613/packages/cookbook/utils/calculate-gas.js#L10 )

**Comment by Vayras** [comment]
Hi, @petersalomonsen I would like to contribute towards this issue, can you please assign me to this, Thank you

**Comment by petersalomonsen** [comment]
Great if you pick it up @Vayras . It is also essential for me to get resolved in order to finish my work here: https://github.com/NearSocial/VM/pull/156#issuecomment-1839408350

**Comment by Vayras** [comment]
Hi, @petersalomonsen can you help me by pointing out the files associated with this issue?

**Comment by elliotBraem** [comment]
Hi @petersalomonsen and @Vayras; 

I've created a PR to the develop branch with my attempt at this story for your review. I've targeted it to develop branch so we can collaborate any further to complete https://github.com/NearSocial/VM/pull/156#issuecomment-1839408350 while ensuring we don't impact production.

I removed the deposit from all function calls to DevHub contract in our codebase, and set the gas for all of them to `Big(10).pow(14)` ([MAX_GAS](https://github.com/near/near-api-js/blob/858b8ee35ffc7d6409b3d72b01f59f4e117db613/packages/cookbook/utils/calculate-gas.js#L10))
