### ISSUE TITLE
Improve sponsorship currency UX

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#74]
[Need to groom story]

[Currently the currency field allows users to enter any field. However, a cryptic error message is return. We need to make it easier for a user to enter the funding amount. We also need to explain the required currency: Main payment options are NEAR tokens or USDC on NEAR].

**Comment by ailisp** [comment]
Currency is now only selectable from NEAR, USDC or USDT so this is no longer an issue
