### ISSUE TITLE
[Communities] Enable permissions for communities – Smart Contract Side

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#81]
**Problem**
Currently, after Community moved to smart contract from hard coded, only admins in DevDAO communities can create communities. Even moderators cannot edit them. This ticket is to introduce the appropriate permissions system for the communities feature on the smart contract side.

**User Stories**
- As a DevHub moderator, I need to have the permission to edit any community so that I can support our communities with any issues that arise.
- As a user with community moderator permissions, I need to have the permissions to edit the relevant items for my community so that I can make the necessary changes without relying on DevDAO developers.

**Acceptance Criteria**
- Moderators can edit any community
- Community admin can edit community, include add or remove another admin of this community

**Technical Implementation**
Since the label based permission system currently does require contract owner (devgovgigs.near) to change any permission rule, we'll come up with some simple straightforward solution:
- (Already in the contract) who already in Community Admin field can edit anything about the community, include add or remove admins
- (To implement in this ticket) moderators can edit any community, regardless of the admin settings

**Comment by ori-near** [comment]
@nearmax @frol @ailisp – Please see this ticket for the proposed "admin" tab and let me know if you have any feedback or concerns. For this MPV, I am leaving the Jira/Kanban management out of scope, which we will solve in a separate ticket.

**Comment by near-akaia-root** [comment]
@ori-near let's change the title to the following:

# [Communities] Store existing communities on chain & add permission control to enable data ownership for community members

**Comment by near-akaia-root** [comment]
Let's also move it to "In progress"
