### ISSUE TITLE
[Communities] Sync GitHub Activity

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#83]
**Problem**
Many communities coordinate their development activity on GitHub, such as [tracking NEPs](https://github.com/orgs/near/projects/51). However, our platform does not show real-time updates from there. This makes it hard for users to discover and keep track of the latest development activities from the communities they care about. It is also difficult for various roles/groups (e.g. Work Group members, DevDAO, etc) to coordinate the monitoring effort of all channels, collect and aggregate feedback, and funnel it into the appropriate pipeline.

**Solution**
Implement a GitHub sync feature that enables each community page to show the latest activity from its corresponding GitHub. This will improve discoverability and engagement for the community, ultimately resulting in more contributions to the ecosystem.

**Acceptance Criteria**
- Integration with GitHub API to retrieve the latest activity 
- Add admin capability for a user with permissions to a specific community to enable a "GitHub" tab and specify the repo pull request URL and label. For example, https://github.com/near/NEPs/pulls and label:WG-protocol
- If a community has GitHub enabled, display a new optional "GitHub" tab for community groups that enabled it, along with the latest activity of all the pull requests (include title, labels, opened on date, author)

**Comment by ori-near** [comment]
Hi @ailisp – a friendly reminder to please add the estimate and any questions you have to this ticket. Thank you!

**Comment by near-akaia-root** [comment]
@ori-near I wanted to take this ticket, but now I see that it's blocked. Does it mean that I should leave it in backlog until the blocking is resolved?

**Comment by ori-near** [comment]
Hi @near-akaia-root – this ticket is partially blocked but @ailisp should resolve it by early next week. 

Somebody could start the work to get the data from GitHub and displaying it on our board. The part that is blocked is connecting it with a specific community & creating the permissions to expose it.

**Comment by near-akaia-root** [comment]
Okay, in this case I'd like to take this ticket to my task pool I'll be working on within the next 2 weeks

**Comment by near-akaia-root** [comment]
Apparently, I can't switch ticket statuses. Could somebody please move this one to “In progress”?

**Comment by near-akaia-root** [comment]
> Integration with GitHub API to retrieve the latest activity

Is it still about the "GitHub" tab or something besides that?

**Comment by ori-near** [comment]
Hi @near-akaia-root – great question. I will update the details of the ticket, but to clarify the big picture: We want to make it easier for people of various communities to see the latest pull requests and their statuses from a GitHub repo that is relevant to their community, such as the [NEP repo](https://github.com/near/NEPs/issues) (NEAR Enhancement Proposals).

For example, today people who care about Protocol NEPs have to go to https://github.com/near/NEPs/pulls and try to sort through the 21+ open NEPs to figure out what are the Protocol NEPs. To make this easier, we created a [Kanban view](https://github.com/orgs/near/projects/51/views/3) on GitHub for the Protocol NEPs that leverages the NEP labels. For example the Protocol NEP Board shows any NEPs that are tagged with the `WG-protocol` label. We want to bring this Kanban view to the DevHub communities. We currently manually move the cards between each column, but ideally we would just set up a rule that would designate which column to use based on the label (e.g. "needs-author-revision" OR "needs-implemenation" labels would all be under DRAFT column, whereas "needs-sme-review" would be under REVIEW).

So for the DevHub: As an admin of the [Protocol community](https://near.social/#/devgovgigs.near/widget/gigs-board.pages.community.Overview?label=protocol), I want to show all the protocol NEPs by their status on DevHub so that protocol community members can find the proposals they care about in one centralized place.

- The admin user has the ability to enable a new "GitHub sync" tab and give it a name (e.g. Protocol NEPs)
- To enable it, they need to specify the following:
   - Tab name
   - GitHub Repo URL(e.g. (https://github.com/near/NEPs) 
   - GitHub data type to pull (PRs and/or Issues)
   - Description text for top of tab (e.g. "This board shows the latest Protocol NEAR Enhancement Proposals by their status. To submit a new NEP, go to x"
   - Specify Kanban # of columns to display (max of 6), their titles, and which labels to filter for each column
- Once admin enables all these fields:
   - DevHub would then pull all the relevant PRs and or Issues, including their issue #, URL, title, labels, and optionally author image and author url. It would be nice to give the admin a confirmation of how many issues come up in the admin view to make sure they set up the connection correctly.
   - A tab shows on the community page with the description and Kanban view, along with all the cards that meet the label filters.

**Comment by near-akaia-root** [comment]
@ori-near how many such tabs should users be able to create?

**Comment by near-akaia-root** [comment]
> Hi @near-akaia-root – that's a good question. Can we start with a limit of one and potentially change this to more in the future?

Yes, definitely! In fact, I've already started with this in mind

**Comment by ori-near** [comment]
Hi @near-akaia-root – I looked at the [preview](https://near.org/root.akaia.near/widget/gigs-board.pages.community.github?label=protocol) you shared and it looks awesome! I noticed a couple of things:

1. The Pull Requests are getting pulled correctly, but the issues are not. For example, at the time of writing this comment there are [10 Open issues](https://github.com/near/NEPs/issues?q=is%3Aopen+is%3Aissue+label%3AWG-protocol) with the `WG-protocol` label. However, when I select in DevHub to pull only issues, it shows 11 items, 3 of which are correct, but the remaining ar PRs.

2. The search terms on DevHub are currently only displaying `OR` conditions. Is there a way to allow AND/OR at the same time? For example, I'd like to show in the REVIEW columns any NEPs that have:
`WG-protocol` label AND (`S-review/needs-sme-review` OR `S-review-needs-author-revision`).

Thank you!

**Comment by frol** [comment]
@ori-near You don’t need to specify every label kind of they share common substring, you can just match “S-review/”. Thus, I would not overcomplicate things with AND logic, at least for now.

**Comment by ori-near** [comment]
Hi @frol – I chatted more with @near-akaia-root about this and we agreed that we don't need to overcomplicate the logic. But we do need at least two AND logic to support pulling labels from a specific workgroup (e.g. WG-protocol) as well as something like the "S-Review" stage. Otherwise, we won't have a way to separate all the "S-Review/" items by group.

**Comment by frol** [comment]
@ori-near Sure, AND logic makes sense to me. I saw a complication in mixing AND/OR logic.

**Comment by near-akaia-root** [comment]
UPD: Replaced OR with AND logic

**Comment by near-akaia-root** [comment]
Ready for review in #123

**Comment by ori-near** [comment]
Thanks so much @near-akaia-root – the latest preview looks amazing.
