### ISSUE TITLE
[Create Post] Save post progress and prevent data loss on cancel

### ISSUE THREAD

**Issue by ori-near** [near/neardevhub-widgets#87]
**Problem**
Currently, when a user creates a new post on our platform and clicks submit, they may lose all their work if something goes wrong on the subsequent screen. We've received several complaints from users about this, as this is causing them frustration and wasted time. 

Example user flow:
- Create a new post (e.g. Idea) and enter all the information into the fields
- Click submit, which prompts the user with the Confirm Transaction pop-up message
- Click confirm, which redirects the user to the Approve Transaction screen
- Click cancel, which redirects the user to the homepage and causes data loss

https://user-images.githubusercontent.com/110252255/230693071-86a7a0f5-e4e9-46ba-9ce7-129ffd046a34.mp4

**User Story**
As a user, I want to have the ability to save my post progress and return to my draft if I accidentally navigate away or close the window, so that I don't lose all my work and can easily pick up where I left off.

**Acceptance Criteria**
- When a creates a new post, clicks submit, and then confirm, if the user clicks cancel or goes back in the browser from the Approve Transaction screen, the user should still see their draft
- Users can submit the saved draft when they are ready to publish it

**Comment by ailisp** [comment]
A major technical challenge I see here is how to let the board know when the post is successfully created and it should clear the draft in this case. Giving this challenge I'm estimating this more than 1 day

**Comment by ailisp** [comment]
@jefedeoro

**Comment by ori-near** [comment]
Hi @ailisp – @jefedeoro is unsure if he can complete this ticket this week, so it's technically open in case anyone else wants to pick it up. But I will add a section to our README that explains how people can get access to this.

**Comment by ben-jamming-reilly** [comment]
@ori-near seems a little tough, but I would like to tackle this one as well

**Comment by frol** [comment]
@ben-jamming-reilly Just a friendly tip: you will probably need [`Storage API`](https://thewiki.near.page/near.social_vm) (scroll it down to "Storage" section)

**Comment by jefedeoro** [comment]
I can help with this ticket.

**Comment by ori-near** [comment]
Hey @jefedeoro – can you please provide a quick update on the progress you've made here and what remains? Based on our conversation today, we will deprioritize this ticket in favor of the Community epic. And you can finish this after.

**Comment by jefedeoro** [comment]
The preview in the first one is just the wrapper without anything in it ( was left open so the wrapped widget would be the content here is a better view for that one sorry https://near.social/#/mob.near/widget/WidgetSource?src=jeffgold.near/widget/LocalStateWidget

the version @ailisp created had a text input for testing the functionality with out having to test within the repo.

**Comment by ori-near** [comment]
Somebody else will need to pick up this ticket at another time.

**Comment by petersalomonsen** [comment]
I would try solving this by storing the draft in localstorage and in case the transaction was cancelled in the wallet, I would then restore the draft from localstorage. Can look into it if nobody else is?

**Comment by near-akaia-root** [comment]
Reassigned to @petersalomonsen
