### ISSUE TITLE
Missing root permission for members

### ISSUE THREAD

**Issue by nearmax** [near/neardevhub-widgets#88]
**Problem**
A moderator role is currently unable to edit posts without a label, preventing them from editing posts.
![Image](https://user-images.githubusercontent.com/110252255/231022320-4bb7f7f6-dd60-43c0-bf9d-3608580d576f.png)

**User Story**
As a moderator role, I want to have the ability to edit any posts, regardless if they have label.

--- 

Details from @nearmax 

Today the way to give a moderator full rights to edit posts on a smart contract level, is to create a permission to edit posts that have labels start with empty string `""`. This is done, because I did not add a specialized permission that represents full editing rights.

The correct fix would be to expand an enum here: https://github.com/near/devgigsboard/blob/2797c37e33bb635b4d63c97a5ba20d1de12ffb70/src/access_control/rules.rs#L49 to include `Rules::Any` variant and then modify https://github.com/near/devgigsboard/blob/2797c37e33bb635b4d63c97a5ba20d1de12ffb70/src/access_control/members.rs#L126 `MembersList::check_permissions` so that for any labels it returns the corresponding action types if account has `Rules::Any`.

**Comment by Tguntenaar** [comment]
@ailisp Could you also assign this to me?

**Comment by ailisp** [comment]
@Tguntenaar FYI This ticket is actually for neardevhub-contract, using Rust. It is a good issue to get started with the contract, build it and have some updates on the contract. Let me know if you have problems working on it.

**Comment by Tguntenaar** [comment]
@near-akaia-root  Could you move it to 'in progress'? Currently blocked by some questions I mentioned in the DRAFT.
